<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nipun Batra">
<meta name="dcterms.date" content="2026-05-21">
<meta name="description" content="Six super-resolution methods tested on a 4× thermal upscaling task (116×87 → 464×348): bicubic, EDSR, MSRN, A2N, DRLN (all RGB-trained CNNs), and Stable Diffusion x4 upscaler (diffusion). Classical CNN-based SR cleanly beats both bicubic and the diffusion upscaler on every metric and on downstream nostril localisation. DRLN tops PSNR/LPIPS; A2N achieves 0.7 px nostril error on a 256-px-wide face. The diffusion upscaler is the most visually sharp but the LEAST accurate downstream — it hallucinates plausible-looking detail that breaks pixel alignment, dropping nose localisation accuracy 7× vs bicubic.">

<title>Thermal Super-Resolution: Can Off-the-Shelf RGB SR Models Upscale Thermal Faces? (Five Methods Head-to-Head) – Nipun Batra Blog</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-b174d82012d95c5b164e50ff853e6622.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-f68a118d2f2af7e6cf8ce6368831e660.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-b174d82012d95c5b164e50ff853e6622.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-796612bf7397dae662d04283c8cc06bc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-ad5c37a8ddeebf8fafae0b1f6b9576d2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-796612bf7397dae662d04283c8cc06bc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta property="og:title" content="Thermal Super-Resolution: Can Off-the-Shelf RGB SR Models Upscale Thermal Faces? (Five Methods Head-to-Head) – Nipun Batra Blog">
<meta property="og:description" content="Six super-resolution methods tested on a 4× thermal upscaling task (116×87 → 464×348): bicubic, EDSR, MSRN, A2N, DRLN (all RGB-trained CNNs), and Stable Diffusion x4 upscaler (diffusion). Classical CNN-based SR cleanly beats both bicubic and the diffusion upscaler on every metric and on downstream nostril localisation. DRLN tops PSNR/LPIPS; A2N achieves 0.7 px nostril error on a 256-px-wide face. The diffusion upscaler is the most visually sharp but the LEAST accurate downstream — it hallucinates plausible-looking detail that breaks pixel alignment, dropping nose localisation accuracy 7× vs bicubic.">
<meta property="og:image" content="thermal-sr/outputs/sr_metrics_chart.png">
<meta property="og:site_name" content="Nipun Batra Blog">
<meta name="twitter:title" content="Thermal Super-Resolution: Can Off-the-Shelf RGB SR Models Upscale Thermal Faces? (Five Methods Head-to-Head) – Nipun Batra Blog">
<meta name="twitter:description" content="Six super-resolution methods tested on a 4× thermal upscaling task (116×87 → 464×348): bicubic, EDSR, MSRN, A2N, DRLN (all RGB-trained CNNs), and Stable Diffusion x4 upscaler (diffusion). Classical CNN-based SR cleanly beats both bicubic and the diffusion upscaler on every metric and on downstream nostril localisation. DRLN tops PSNR/LPIPS; A2N achieves 0.7 px nostril error on a 256-px-wide face. The diffusion upscaler is the most visually sharp but the LEAST accurate downstream — it hallucinates plausible-looking detail that breaks pixel alignment, dropping nose localisation accuracy 7× vs bicubic.">
<meta name="twitter:image" content="thermal-sr/outputs/sr_metrics_chart.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Nipun Batra Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://nipunbatra.github.io"> 
<span class="menu-text">Homepage</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Thermal Super-Resolution: Can Off-the-Shelf RGB SR Models Upscale Thermal Faces? (Five Methods Head-to-Head)</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                  <div>
        <div class="description">
          Six super-resolution methods tested on a 4× thermal upscaling task (116×87 → 464×348): bicubic, EDSR, MSRN, A2N, DRLN (all RGB-trained CNNs), and Stable Diffusion x4 upscaler (diffusion). Classical CNN-based SR cleanly beats both bicubic and the diffusion upscaler on every metric and on downstream nostril localisation. DRLN tops PSNR/LPIPS; A2N achieves 0.7 px nostril error on a 256-px-wide face. The diffusion upscaler is the most visually sharp but the LEAST accurate downstream — it hallucinates plausible-looking detail that breaks pixel alignment, dropping nose localisation accuracy 7× vs bicubic.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">thermal-imaging</div>
                <div class="quarto-category">super-resolution</div>
                <div class="quarto-category">ESRGAN</div>
                <div class="quarto-category">EDSR</div>
                <div class="quarto-category">DRLN</div>
                <div class="quarto-category">MSRN</div>
                <div class="quarto-category">A2N</div>
                <div class="quarto-category">Stable-Diffusion</div>
                <div class="quarto-category">image-restoration</div>
                <div class="quarto-category">paper-prototype</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Nipun Batra </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 21, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-motivation" id="toc-the-motivation" class="nav-link active" data-scroll-target="#the-motivation">The motivation</a></li>
  <li><a href="#the-protocol" id="toc-the-protocol" class="nav-link" data-scroll-target="#the-protocol">The protocol</a></li>
  <li><a href="#the-six-methods" id="toc-the-six-methods" class="nav-link" data-scroll-target="#the-six-methods">The six methods</a></li>
  <li><a href="#headline-result" id="toc-headline-result" class="nav-link" data-scroll-target="#headline-result">Headline result</a></li>
  <li><a href="#what-the-outputs-actually-look-like" id="toc-what-the-outputs-actually-look-like" class="nav-link" data-scroll-target="#what-the-outputs-actually-look-like">What the outputs actually look like</a></li>
  <li><a href="#why-does-diffusion-lose-to-a-2017-cnn" id="toc-why-does-diffusion-lose-to-a-2017-cnn" class="nav-link" data-scroll-target="#why-does-diffusion-lose-to-a-2017-cnn">Why does diffusion lose to a 2017 CNN?</a></li>
  <li><a href="#how-this-connects-to-the-pbvs-tisr-challenge" id="toc-how-this-connects-to-the-pbvs-tisr-challenge" class="nav-link" data-scroll-target="#how-this-connects-to-the-pbvs-tisr-challenge">How this connects to the PBVS TISR Challenge</a></li>
  <li><a href="#three-caveats" id="toc-three-caveats" class="nav-link" data-scroll-target="#three-caveats">Three caveats</a></li>
  <li><a href="#whats-actually-deployable-today" id="toc-whats-actually-deployable-today" class="nav-link" data-scroll-target="#whats-actually-deployable-today">What’s actually deployable today</a></li>
  <li><a href="#links" id="toc-links" class="nav-link" data-scroll-target="#links">Links</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">






<section id="the-motivation" class="level2">
<h2 class="anchored" data-anchor-id="the-motivation">The motivation</h2>
<p>Thermal cameras have low native resolution. The Lepton 3.5 is 160×120, the TC001+ used in <a href="https://www.kaggle.com/datasets/shriayush/thermeval">ThermEval-D</a> is 256×192, even the high-end FLIR Boson tops out at 640×512. Downstream tasks — face detection, nostril localisation for breath-rate, fever screening — get easier when the face occupies more pixels. So super-resolution is the obvious lever.</p>
<p>The question I want to answer: <strong>does off-the-shelf, RGB-trained super-resolution actually help on thermal?</strong> The same modality-gap reasoning from <a href="../posts/2026-05-21-thermal-image-generation-gemini.html">the Gemini thermal-generation post</a> applies: a SR model trained on millions of RGB image pairs has learned to synthesise <em>RGB textures</em> (skin pores, hair strands, eyelash detail). Those textures don’t exist on thermal. Will the model hallucinate them anyway and ruin the image, or will it just sharpen the existing thermal content?</p>
<p>This experiment runs <strong>six SR methods</strong> on the same task — downsample a real LWIR thermal face 4× to simulate a Lepton-class camera, then restore — and scores them on pixel-similarity AND downstream nostril localisation. The latter is the deployment-relevant metric.</p>
<blockquote class="blockquote">
<p>Code: <a href="https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/run_super_res.py"><code>posts/thermal-sr/scripts/run_super_res.py</code></a>.</p>
</blockquote>
</section>
<section id="the-protocol" class="level2">
<h2 class="anchored" data-anchor-id="the-protocol">The protocol</h2>
<ol type="1">
<li><strong>HR thermal</strong>: the SF-TL54 sample frame (464×348, iron palette) — same image used in the rest of the <a href="../posts/2026-05-20-thermal-nostril-bakeoff.html">thermal-nostril series</a>.</li>
<li><strong>Degradation</strong>: <code>cv2.resize(..., INTER_AREA)</code> 4× down to <strong>116×87</strong> — roughly the resolution of a Lepton 3.5.</li>
<li><strong>Restoration</strong>: each SR method takes the 116×87 image and produces a 464×348 output.</li>
<li><strong>Evaluation</strong>:
<ul>
<li><strong>PSNR / SSIM</strong> against the HR thermal — classical pixel similarity.</li>
<li><strong>LPIPS</strong> (AlexNet) — perceptual similarity.</li>
<li><strong>Sharpness</strong> = Laplacian variance — high-frequency content.</li>
<li><strong>DWPose nostril error</strong> — run <a href="https://github.com/Tau-J/rtmlib">DWPose body-keypoint detector</a> on each restored image and on the HR target; report the pixel distance between the two predicted nostril positions. This is the “does the SR preserve face geometry for a downstream model?” metric.</li>
</ul></li>
</ol>
<p>Note the choice of an x4 downscale-and-restore protocol — this is the <a href="https://codalab.lisn.upsaclay.fr/competitions/17013">PBVS Thermal Image SR Challenge</a> protocol for Track-1 (single-image super-resolution). The challenge’s 2024 winning entries used custom thermal-trained models; here we test what off-the-shelf RGB-trained SR achieves zero-shot.</p>
</section>
<section id="the-six-methods" class="level2">
<h2 class="anchored" data-anchor-id="the-six-methods">The six methods</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Year</th>
<th>Family</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Bicubic</strong></td>
<td>classical</td>
<td>Interpolation baseline</td>
<td>OpenCV <code>INTER_CUBIC</code></td>
</tr>
<tr class="even">
<td><strong>EDSR</strong></td>
<td>ECCV 2017</td>
<td>Residual CNN</td>
<td><code>eugenesiow/edsr-base</code> (super-image)</td>
</tr>
<tr class="odd">
<td><strong>MSRN</strong></td>
<td>ECCV 2018</td>
<td>Multi-scale CNN</td>
<td><code>eugenesiow/msrn</code></td>
</tr>
<tr class="even">
<td><strong>A2N</strong></td>
<td>CVPR 2021</td>
<td>Attention CNN</td>
<td><code>eugenesiow/a2n</code></td>
</tr>
<tr class="odd">
<td><strong>DRLN</strong></td>
<td>TPAMI 2020</td>
<td>Dense residual CNN</td>
<td><code>eugenesiow/drln-bam</code></td>
</tr>
<tr class="even">
<td><strong>SD x4 upscaler</strong></td>
<td>2023</td>
<td>Diffusion (caption-conditioned)</td>
<td><code>stabilityai/stable-diffusion-x4-upscaler</code></td>
</tr>
</tbody>
</table>
<p>All six were trained on RGB image pairs (DIV2K + Flickr2K). None has seen LWIR thermal during training.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bicubic — trivially fast</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>lr_to_hr <span class="op">=</span> cv2.resize(lr, (W, H), interpolation<span class="op">=</span>cv2.INTER_CUBIC)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># EDSR / MSRN / A2N / DRLN — via super-image package</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> super_image <span class="im">import</span> EdsrModel, ImageLoader</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> EdsrModel.from_pretrained(<span class="st">"eugenesiow/edsr-base"</span>, scale<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>out <span class="op">=</span> model(ImageLoader.load_image(lr_pil))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Stable Diffusion x4 upscaler — diffusion with prompt conditioning</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> diffusers <span class="im">import</span> StableDiffusionUpscalePipeline</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>pipe <span class="op">=</span> StableDiffusionUpscalePipeline.from_pretrained(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"stabilityai/stable-diffusion-x4-upscaler"</span>, torch_dtype<span class="op">=</span>torch.float16).to(<span class="st">"cuda"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>sr <span class="op">=</span> pipe(prompt<span class="op">=</span><span class="st">"a thermal infrared face image"</span>, image<span class="op">=</span>lr_pil,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>          num_inference_steps<span class="op">=</span><span class="dv">20</span>).images[<span class="dv">0</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="headline-result" class="level2">
<h2 class="anchored" data-anchor-id="headline-result">Headline result</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="thermal-sr/outputs/sr_metrics_chart.png" class="img-fluid figure-img"></p>
<figcaption>Four-panel comparison across six methods on the 4× thermal SR task. Classical CNN-based SR (EDSR, MSRN, A2N, DRLN) all dominate bicubic AND the diffusion upscaler on every metric. Stable Diffusion x4 upscaler has the worst PSNR (27.0) and the worst nose error (18.8 px) despite being the visually “sharpest” output.</figcaption>
</figure>
</div>
<p>Full numbers:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th style="text-align: right;">PSNR ↑</th>
<th style="text-align: right;">SSIM ↑</th>
<th style="text-align: right;">LPIPS ↓</th>
<th style="text-align: right;">Sharpness</th>
<th style="text-align: right;"><strong>Nose err (px) ↓</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bicubic</td>
<td style="text-align: right;">34.38</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">0.045</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">2.67</td>
</tr>
<tr class="even">
<td>EDSR x4</td>
<td style="text-align: right;">36.97</td>
<td style="text-align: right;"><strong>0.984</strong></td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">11.3</td>
<td style="text-align: right;">1.36</td>
</tr>
<tr class="odd">
<td>MSRN x4</td>
<td style="text-align: right;">37.09</td>
<td style="text-align: right;"><strong>0.984</strong></td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">1.65</td>
</tr>
<tr class="even">
<td>A2N x4</td>
<td style="text-align: right;">36.68</td>
<td style="text-align: right;">0.983</td>
<td style="text-align: right;">0.023</td>
<td style="text-align: right;">11.6</td>
<td style="text-align: right;"><strong>0.70</strong></td>
</tr>
<tr class="odd">
<td><strong>DRLN x4</strong></td>
<td style="text-align: right;"><strong>37.41</strong></td>
<td style="text-align: right;"><strong>0.984</strong></td>
<td style="text-align: right;"><strong>0.021</strong></td>
<td style="text-align: right;">13.0</td>
<td style="text-align: right;">1.14</td>
</tr>
<tr class="even">
<td>SD x4 upscaler</td>
<td style="text-align: right;">27.01</td>
<td style="text-align: right;">0.894</td>
<td style="text-align: right;">0.112</td>
<td style="text-align: right;">30.5</td>
<td style="text-align: right;">18.81</td>
</tr>
</tbody>
</table>
<p>Three things to call out:</p>
<ol type="1">
<li><strong>EDSR / MSRN / A2N / DRLN are all very close</strong> to each other on pixel metrics (PSNR 36.7–37.4, SSIM 0.983–0.984, LPIPS 0.021–0.023). They’re all roughly the same off-the-shelf option for thermal SR.</li>
<li><strong>DRLN wins on PSNR/LPIPS; A2N wins on downstream nostril localisation.</strong> Pick by use case: if you need pixel-faithful restoration, DRLN. If you need face-geometry preservation, A2N.</li>
<li><strong>Stable Diffusion x4 upscaler is dramatically worse on everything that matters</strong> — 10 dB lower PSNR than the classical CNNs, 7× worse nostril localisation than bicubic. But the highest “sharpness” (30.5 vs 13.0). The model is adding sharp detail; it’s just <em>wrong</em> sharp detail.</li>
</ol>
</section>
<section id="what-the-outputs-actually-look-like" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="what-the-outputs-actually-look-like">What the outputs actually look like</h2>
<div class="page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="thermal-sr/outputs/sr_side_by_side.png" class="img-fluid figure-img column-page"></p>
<figcaption>Six methods side by side. Top row: HR target (left), LR input nearest-neighbour-upsampled for display (right). Subsequent rows: each restored method with its per-image PSNR/LPIPS/nose_err.</figcaption>
</figure>
</div>
</div>
<p>Reading the panel:</p>
<ul>
<li><strong>HR target</strong> (top-left): the real SF-TL54 thermal, 464×348, iron palette. Eyes closed (dark eyelids), warm forehead, cool hair, the characteristic cold spot at the nose tip.</li>
<li><strong>LR input</strong> displayed nearest-neighbour: the 116×87 source after 4× downsample. Roughly recognisable but the nose / mouth area is below the pixel grid.</li>
<li><strong>Bicubic</strong>: smooth but blurry. PSNR 34.4 — decent because it doesn’t add wrong content, just lacks detail.</li>
<li><strong>EDSR / MSRN / A2N / DRLN</strong>: all visually very similar to the HR target. Eyebrows sharpened, eyelids preserved, hair texture restored. These are doing the right thing.</li>
<li><strong>SD x4 upscaler</strong>: visibly <em>different</em> face proportions. The model has interpreted the LR thermal as “a low-quality RGB face” and tried to inpaint plausible RGB textures — which alter the head shape and lose the cold-nose signature entirely.</li>
</ul>
</section>
<section id="why-does-diffusion-lose-to-a-2017-cnn" class="level2">
<h2 class="anchored" data-anchor-id="why-does-diffusion-lose-to-a-2017-cnn">Why does diffusion lose to a 2017 CNN?</h2>
<p>Three reasons, in increasing order of importance for the paper:</p>
<ol type="1">
<li><p><strong>Caption conditioning is a foreign prior.</strong> SD x4 upscaler is conditioned on a text prompt (“a thermal infrared face image” in my test). The text encoder pulls in priors from RGB-thermal-style images on the internet — mostly Wikipedia FLIR demos with glowing eyes — which then bias the diffusion to add those features. The classical CNNs have no text input; they just super-resolve the pixels.</p></li>
<li><p><strong>Diffusion’s sampler injects noise.</strong> Each diffusion step adds Gaussian noise and learns to denoise. On a high-fidelity restoration task with very little degradation (4× downscale is mild), the noise budget <em>exceeds</em> the signal we care about. The “sharper” output is sharper because diffusion <em>invented</em> detail consistent with its training distribution, not because it recovered detail from the LR.</p></li>
<li><p><strong>The metric structure favours conservative methods.</strong> PSNR rewards “leave the pixels close to ground truth”; classical CNNs minimise an L2-like reconstruction loss that maps directly to PSNR. Diffusion is trained to produce <em>plausible</em> images, not <em>pixel-accurate</em> images. Different objectives → different metrics → different leaders.</p></li>
</ol>
<p>The paper-relevant observation is <strong>(3)</strong>: when downstream-task accuracy is the goal, the right SR objective is pixel reconstruction, not perceptual realism. The diffusion-upscaler “wins” on subjective sharpness but loses every metric and breaks the downstream task.</p>
</section>
<section id="how-this-connects-to-the-pbvs-tisr-challenge" class="level2">
<h2 class="anchored" data-anchor-id="how-this-connects-to-the-pbvs-tisr-challenge">How this connects to the PBVS TISR Challenge</h2>
<p>The <a href="https://pbvs-workshop.github.io/challenge.html">PBVS Thermal Image SR Challenge</a> (now in its 7th iteration via the <a href="https://www.codabench.org/competitions/12339/">Codabench portal</a>) is exactly the right venue for paper-grade work on this. Track-1 of the 2024 challenge ran a single-image SR task at ×8 scale on a thermal-specific dataset (CIDIS, 1000 thermal-RGB pairs). Track-2 was RGB-guided thermal SR at ×8 and ×16.</p>
<p>The winning entries (e.g., the <a href="https://github.com/Raojiyong/PBVS_TSR">DRCT-L-X4-based PBVS 2025 winner</a>) all do the same two things:</p>
<ol type="1">
<li><strong>Pretrain on RGB SR data</strong> (DIV2K + Flickr2K) — to get a working backbone.</li>
<li><strong>Finetune on thermal-specific pairs</strong> (the CIDIS or M3FD thermal sets) — to bend the model toward thermal texture statistics.</li>
</ol>
<p>The combination beats either alone. My zero-shot result above is the upper bound on what step 1 buys you without step 2 — and it’s quite a lot: DRLN at PSNR 37.4 zero-shot is in the same league as some 2022-2023 papers that <em>did</em> finetune on thermal. The marginal value of finetuning on thermal is real but smaller than expected, because thermal is <em>closer</em> to grayscale RGB than to a fundamentally different modality.</p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>For paper submission to PBVS TISR</strong>: take an off-the-shelf classical CNN (DRLN or similar), finetune on the CIDIS thermal training set for 50-100 epochs at LR 1e-4. Cost: a few hours on a single GPU. Likely result: PSNR up another 1-2 dB over the zero-shot version, putting you in the top 10 of a typical TISR leaderboard. <strong>Bonus</strong>: add a downstream-task loss (LPIPS to a thermal-face landmarker’s output) to constrain “the output should preserve face geometry for downstream models” — this is what the leaderboard doesn’t yet measure but should.</p>
</div>
</div>
</div>
</section>
<section id="three-caveats" class="level2">
<h2 class="anchored" data-anchor-id="three-caveats">Three caveats</h2>
<ul>
<li><strong>N=1 sample.</strong> This is the same SF-TL54 portrait used in the other thermal posts. For paper-grade claims you’d run on the full CIDIS test set (100 images) and report mean ± std.</li>
<li><strong>Iron palette inputs.</strong> The SF-TL54 images are iron-palette colour-mapped — they have 3 channels. A raw radiometric thermal frame is single-channel float; the SR models trained on RGB are running over a “fake-RGB” input here. A model trained directly on radiometric float would be different (and presumably better at preserving the underlying temperature signal). Adapt your SR model’s first conv layer accordingly.</li>
<li><strong>No physical losses.</strong> The metrics here (PSNR/SSIM/LPIPS) are perceptual/photometric. They don’t directly measure “did the restored image preserve the <em>temperature</em> signal at every pixel” — which is what a downstream physical task (fever screening, breath rate) actually cares about. The right thing to add for thermal SR specifically is a <strong>temperature-preservation loss</strong>: L1 between the restored and HR pixel intensities <em>in radiometric units</em> (after the iron-palette colormap inverse), weighted higher in the face region.</li>
</ul>
</section>
<section id="whats-actually-deployable-today" class="level2">
<h2 class="anchored" data-anchor-id="whats-actually-deployable-today">What’s actually deployable today</h2>
<p>If you have a Lepton-class thermal camera and want a real-time SR pipeline for a downstream face-aware task:</p>
<ol type="1">
<li><strong>Use a classical CNN super-resolver</strong> (EDSR/MSRN/A2N/DRLN). They all sit at PSNR 37, LPIPS 0.02 zero-shot.</li>
<li><strong>Pick by downstream-task accuracy</strong>, not perceptual sharpness. A2N had the best nostril-localisation accuracy in my test (0.7 px); DRLN had the best LPIPS. Test both on <em>your</em> downstream task before choosing.</li>
<li><strong>Don’t use a diffusion upscaler</strong>. It looks sharper, breaks everything.</li>
<li><strong>If you have ground-truth thermal data</strong>, finetune the chosen classical CNN on it. That’s what every PBVS TISR winner does.</li>
</ol>
</section>
<section id="links" class="level2">
<h2 class="anchored" data-anchor-id="links">Links</h2>
<ul>
<li>Experiment script: <a href="https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/run_super_res.py"><code>posts/thermal-sr/scripts/run_super_res.py</code></a></li>
<li>Companion thermal posts: <a href="../posts/2026-05-21-thermal-image-generation-gemini.html">Gemini thermal generation</a> · <a href="../posts/2026-05-20-thermal-nostril-bakeoff.html">thermal nostril series part 1</a></li>
<li>PBVS Thermal Image SR Challenge: <a href="https://pbvs-workshop.github.io/challenge.html">pbvs-workshop.github.io/challenge.html</a> · <a href="https://www.codabench.org/competitions/12339/">active Codabench leaderboard</a></li>
<li>PBVS 2025 winning solution (DRCT-L-X4): <a href="https://github.com/Raojiyong/PBVS_TSR">Raojiyong/PBVS_TSR</a></li>
<li>PBVS 2024 2nd-place: <a href="https://github.com/upczww/TISR">upczww/TISR</a></li>
<li>Cross-spectral SR: <a href="https://arxiv.org/abs/2404.14533">SwinFuSR</a></li>
<li>Survey: <a href="https://github.com/yongsongH/Infrared_Image_SR_Survey">Infrared Image SR Survey (yongsongH)</a></li>
<li>Awesome Thermal SR list: <a href="https://github.com/zhgqcn/awesome-Thermal-Image-Super-Resolution">zhgqcn/awesome-Thermal-Image-Super-Resolution</a></li>
<li>Super-image package: <a href="https://github.com/eugenesiow/super-image">eugenesiow/super-image</a></li>
<li>Stable Diffusion x4 upscaler: <a href="https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler">stabilityai/stable-diffusion-x4-upscaler</a></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            trigger: 'click',
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            positionFixed: true,
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Thermal Super-Resolution: Can Off-the-Shelf RGB SR Models Upscale Thermal Faces? (Five Methods Head-to-Head)"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Nipun Batra"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-05-21"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [thermal-imaging, super-resolution, ESRGAN, EDSR, DRLN, MSRN, A2N, Stable-Diffusion, image-restoration, paper-prototype]</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Six super-resolution methods tested on a 4× thermal upscaling task (116×87 → 464×348): bicubic, EDSR, MSRN, A2N, DRLN (all RGB-trained CNNs), and Stable Diffusion x4 upscaler (diffusion). Classical CNN-based SR cleanly beats both bicubic and the diffusion upscaler on every metric and on downstream nostril localisation. DRLN tops PSNR/LPIPS; A2N achieves 0.7 px nostril error on a 256-px-wide face. The diffusion upscaler is the most visually sharp but the LEAST accurate downstream — it hallucinates plausible-looking detail that breaks pixel alignment, dropping nose localisation accuracy 7× vs bicubic."</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="an">resources:</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - thermal-sr/scripts/*.py</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - thermal-sr/outputs/*.png</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - thermal-sr/outputs/*.json</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## The motivation</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>Thermal cameras have low native resolution. The Lepton 3.5 is 160×120, the TC001+ used in <span class="co">[</span><span class="ot">ThermEval-D</span><span class="co">](https://www.kaggle.com/datasets/shriayush/thermeval)</span> is 256×192, even the high-end FLIR Boson tops out at 640×512. Downstream tasks — face detection, nostril localisation for breath-rate, fever screening — get easier when the face occupies more pixels. So super-resolution is the obvious lever.</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>The question I want to answer: **does off-the-shelf, RGB-trained super-resolution actually help on thermal?** The same modality-gap reasoning from <span class="co">[</span><span class="ot">the Gemini thermal-generation post</span><span class="co">](2026-05-21-thermal-image-generation-gemini.qmd)</span> applies: a SR model trained on millions of RGB image pairs has learned to synthesise *RGB textures* (skin pores, hair strands, eyelash detail). Those textures don't exist on thermal. Will the model hallucinate them anyway and ruin the image, or will it just sharpen the existing thermal content?</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>This experiment runs **six SR methods** on the same task — downsample a real LWIR thermal face 4× to simulate a Lepton-class camera, then restore — and scores them on pixel-similarity AND downstream nostril localisation. The latter is the deployment-relevant metric.</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Code: </span><span class="co">[</span><span class="ot">`posts/thermal-sr/scripts/run_super_res.py`</span><span class="co">](https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/run_super_res.py)</span><span class="at">.</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## The protocol</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**HR thermal**: the SF-TL54 sample frame (464×348, iron palette) — same image used in the rest of the <span class="co">[</span><span class="ot">thermal-nostril series</span><span class="co">](2026-05-20-thermal-nostril-bakeoff.qmd)</span>.</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Degradation**: `cv2.resize(..., INTER_AREA)` 4× down to **116×87** — roughly the resolution of a Lepton 3.5.</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Restoration**: each SR method takes the 116×87 image and produces a 464×348 output.</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Evaluation**:</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>**PSNR / SSIM** against the HR thermal — classical pixel similarity.</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>**LPIPS** (AlexNet) — perceptual similarity.</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>**Sharpness** = Laplacian variance — high-frequency content.</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a><span class="ss">   - </span>**DWPose nostril error** — run <span class="co">[</span><span class="ot">DWPose body-keypoint detector</span><span class="co">](https://github.com/Tau-J/rtmlib)</span> on each restored image and on the HR target; report the pixel distance between the two predicted nostril positions. This is the "does the SR preserve face geometry for a downstream model?" metric.</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>Note the choice of an x4 downscale-and-restore protocol — this is the <span class="co">[</span><span class="ot">PBVS Thermal Image SR Challenge</span><span class="co">](https://codalab.lisn.upsaclay.fr/competitions/17013)</span> protocol for Track-1 (single-image super-resolution). The challenge's 2024 winning entries used custom thermal-trained models; here we test what off-the-shelf RGB-trained SR achieves zero-shot.</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="fu">## The six methods</span></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Method <span class="pp">|</span> Year <span class="pp">|</span> Family <span class="pp">|</span> Source <span class="pp">|</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------|------|--------|--------|</span></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Bicubic** <span class="pp">|</span> classical <span class="pp">|</span> Interpolation baseline <span class="pp">|</span> OpenCV <span class="in">`INTER_CUBIC`</span> <span class="pp">|</span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **EDSR** <span class="pp">|</span> ECCV 2017 <span class="pp">|</span> Residual CNN <span class="pp">|</span> <span class="in">`eugenesiow/edsr-base`</span> (super-image) <span class="pp">|</span></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **MSRN** <span class="pp">|</span> ECCV 2018 <span class="pp">|</span> Multi-scale CNN <span class="pp">|</span> <span class="in">`eugenesiow/msrn`</span> <span class="pp">|</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **A2N** <span class="pp">|</span> CVPR 2021 <span class="pp">|</span> Attention CNN <span class="pp">|</span> <span class="in">`eugenesiow/a2n`</span> <span class="pp">|</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **DRLN** <span class="pp">|</span> TPAMI 2020 <span class="pp">|</span> Dense residual CNN <span class="pp">|</span> <span class="in">`eugenesiow/drln-bam`</span> <span class="pp">|</span></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **SD x4 upscaler** <span class="pp">|</span> 2023 <span class="pp">|</span> Diffusion (caption-conditioned) <span class="pp">|</span> <span class="in">`stabilityai/stable-diffusion-x4-upscaler`</span> <span class="pp">|</span></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>All six were trained on RGB image pairs (DIV2K + Flickr2K). None has seen LWIR thermal during training.</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Bicubic — trivially fast</span></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>lr_to_hr <span class="op">=</span> cv2.resize(lr, (W, H), interpolation<span class="op">=</span>cv2.INTER_CUBIC)</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a><span class="co"># EDSR / MSRN / A2N / DRLN — via super-image package</span></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> super_image <span class="im">import</span> EdsrModel, ImageLoader</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> EdsrModel.from_pretrained(<span class="st">"eugenesiow/edsr-base"</span>, scale<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>out <span class="op">=</span> model(ImageLoader.load_image(lr_pil))</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Stable Diffusion x4 upscaler — diffusion with prompt conditioning</span></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> diffusers <span class="im">import</span> StableDiffusionUpscalePipeline</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>pipe <span class="op">=</span> StableDiffusionUpscalePipeline.from_pretrained(</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>    <span class="st">"stabilityai/stable-diffusion-x4-upscaler"</span>, torch_dtype<span class="op">=</span>torch.float16).to(<span class="st">"cuda"</span>)</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>sr <span class="op">=</span> pipe(prompt<span class="op">=</span><span class="st">"a thermal infrared face image"</span>, image<span class="op">=</span>lr_pil,</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>          num_inference_steps<span class="op">=</span><span class="dv">20</span>).images[<span class="dv">0</span>]</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a><span class="fu">## Headline result</span></span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a><span class="al">![Four-panel comparison across six methods on the 4× thermal SR task. Classical CNN-based SR (EDSR, MSRN, A2N, DRLN) all dominate bicubic AND the diffusion upscaler on every metric. Stable Diffusion x4 upscaler has the worst PSNR (27.0) and the worst nose error (18.8 px) despite being the visually "sharpest" output.](thermal-sr/outputs/sr_metrics_chart.png)</span></span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>Full numbers:</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Method <span class="pp">|</span> PSNR ↑ <span class="pp">|</span> SSIM ↑ <span class="pp">|</span> LPIPS ↓ <span class="pp">|</span> Sharpness <span class="pp">|</span> **Nose err (px) ↓** <span class="pp">|</span></span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------|-------:|-------:|--------:|----------:|--------------------:|</span></span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Bicubic <span class="pp">|</span> 34.38 <span class="pp">|</span> 0.978 <span class="pp">|</span> 0.045 <span class="pp">|</span> 4.1 <span class="pp">|</span> 2.67 <span class="pp">|</span></span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> EDSR x4 <span class="pp">|</span> 36.97 <span class="pp">|</span> **0.984** <span class="pp">|</span> 0.022 <span class="pp">|</span> 11.3 <span class="pp">|</span> 1.36 <span class="pp">|</span></span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> MSRN x4 <span class="pp">|</span> 37.09 <span class="pp">|</span> **0.984** <span class="pp">|</span> 0.022 <span class="pp">|</span> 12.0 <span class="pp">|</span> 1.65 <span class="pp">|</span></span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> A2N x4 <span class="pp">|</span> 36.68 <span class="pp">|</span> 0.983 <span class="pp">|</span> 0.023 <span class="pp">|</span> 11.6 <span class="pp">|</span> **0.70** <span class="pp">|</span></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **DRLN x4** | **37.41** | **0.984** | **0.021** <span class="pp">|</span> 13.0 <span class="pp">|</span> 1.14 <span class="pp">|</span></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> SD x4 upscaler <span class="pp">|</span> 27.01 <span class="pp">|</span> 0.894 <span class="pp">|</span> 0.112 <span class="pp">|</span> 30.5 <span class="pp">|</span> 18.81 <span class="pp">|</span></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a>Three things to call out:</span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**EDSR / MSRN / A2N / DRLN are all very close** to each other on pixel metrics (PSNR 36.7–37.4, SSIM 0.983–0.984, LPIPS 0.021–0.023). They're all roughly the same off-the-shelf option for thermal SR.</span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**DRLN wins on PSNR/LPIPS; A2N wins on downstream nostril localisation.** Pick by use case: if you need pixel-faithful restoration, DRLN. If you need face-geometry preservation, A2N.</span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Stable Diffusion x4 upscaler is dramatically worse on everything that matters** — 10 dB lower PSNR than the classical CNNs, 7× worse nostril localisation than bicubic. But the highest "sharpness" (30.5 vs 13.0). The model is adding sharp detail; it's just *wrong* sharp detail.</span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a><span class="fu">## What the outputs actually look like</span></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a>::: {.column-page}</span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a><span class="al">![Six methods side by side. Top row: HR target (left), LR input nearest-neighbour-upsampled for display (right). Subsequent rows: each restored method with its per-image PSNR/LPIPS/nose_err.](thermal-sr/outputs/sr_side_by_side.png)</span></span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a>Reading the panel:</span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**HR target** (top-left): the real SF-TL54 thermal, 464×348, iron palette. Eyes closed (dark eyelids), warm forehead, cool hair, the characteristic cold spot at the nose tip.</span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**LR input** displayed nearest-neighbour: the 116×87 source after 4× downsample. Roughly recognisable but the nose / mouth area is below the pixel grid.</span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Bicubic**: smooth but blurry. PSNR 34.4 — decent because it doesn't add wrong content, just lacks detail.</span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**EDSR / MSRN / A2N / DRLN**: all visually very similar to the HR target. Eyebrows sharpened, eyelids preserved, hair texture restored. These are doing the right thing.</span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**SD x4 upscaler**: visibly *different* face proportions. The model has interpreted the LR thermal as "a low-quality RGB face" and tried to inpaint plausible RGB textures — which alter the head shape and lose the cold-nose signature entirely.</span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why does diffusion lose to a 2017 CNN?</span></span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a>Three reasons, in increasing order of importance for the paper:</span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Caption conditioning is a foreign prior.** SD x4 upscaler is conditioned on a text prompt ("a thermal infrared face image" in my test). The text encoder pulls in priors from RGB-thermal-style images on the internet — mostly Wikipedia FLIR demos with glowing eyes — which then bias the diffusion to add those features. The classical CNNs have no text input; they just super-resolve the pixels.</span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Diffusion's sampler injects noise.** Each diffusion step adds Gaussian noise and learns to denoise. On a high-fidelity restoration task with very little degradation (4× downscale is mild), the noise budget *exceeds* the signal we care about. The "sharper" output is sharper because diffusion *invented* detail consistent with its training distribution, not because it recovered detail from the LR.</span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**The metric structure favours conservative methods.** PSNR rewards "leave the pixels close to ground truth"; classical CNNs minimise an L2-like reconstruction loss that maps directly to PSNR. Diffusion is trained to produce *plausible* images, not *pixel-accurate* images. Different objectives → different metrics → different leaders.</span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a>The paper-relevant observation is **(3)**: when downstream-task accuracy is the goal, the right SR objective is pixel reconstruction, not perceptual realism. The diffusion-upscaler "wins" on subjective sharpness but loses every metric and breaks the downstream task.</span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a><span class="fu">## How this connects to the PBVS TISR Challenge</span></span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a>The <span class="co">[</span><span class="ot">PBVS Thermal Image SR Challenge</span><span class="co">](https://pbvs-workshop.github.io/challenge.html)</span> (now in its 7th iteration via the <span class="co">[</span><span class="ot">Codabench portal</span><span class="co">](https://www.codabench.org/competitions/12339/)</span>) is exactly the right venue for paper-grade work on this. Track-1 of the 2024 challenge ran a single-image SR task at ×8 scale on a thermal-specific dataset (CIDIS, 1000 thermal-RGB pairs). Track-2 was RGB-guided thermal SR at ×8 and ×16.</span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a>The winning entries (e.g., the <span class="co">[</span><span class="ot">DRCT-L-X4-based PBVS 2025 winner</span><span class="co">](https://github.com/Raojiyong/PBVS_TSR)</span>) all do the same two things:</span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Pretrain on RGB SR data** (DIV2K + Flickr2K) — to get a working backbone.</span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Finetune on thermal-specific pairs** (the CIDIS or M3FD thermal sets) — to bend the model toward thermal texture statistics.</span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a>The combination beats either alone. My zero-shot result above is the upper bound on what step 1 buys you without step 2 — and it's quite a lot: DRLN at PSNR 37.4 zero-shot is in the same league as some 2022-2023 papers that *did* finetune on thermal. The marginal value of finetuning on thermal is real but smaller than expected, because thermal is *closer* to grayscale RGB than to a fundamentally different modality.</span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip appearance="simple"}</span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a>**For paper submission to PBVS TISR**: take an off-the-shelf classical CNN (DRLN or similar), finetune on the CIDIS thermal training set for 50-100 epochs at LR 1e-4. Cost: a few hours on a single GPU. Likely result: PSNR up another 1-2 dB over the zero-shot version, putting you in the top 10 of a typical TISR leaderboard. **Bonus**: add a downstream-task loss (LPIPS to a thermal-face landmarker's output) to constrain "the output should preserve face geometry for downstream models" — this is what the leaderboard doesn't yet measure but should.</span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a><span class="fu">## Three caveats</span></span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**N=1 sample.** This is the same SF-TL54 portrait used in the other thermal posts. For paper-grade claims you'd run on the full CIDIS test set (100 images) and report mean ± std.</span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Iron palette inputs.** The SF-TL54 images are iron-palette colour-mapped — they have 3 channels. A raw radiometric thermal frame is single-channel float; the SR models trained on RGB are running over a "fake-RGB" input here. A model trained directly on radiometric float would be different (and presumably better at preserving the underlying temperature signal). Adapt your SR model's first conv layer accordingly.</span>
<span id="cb2-137"><a href="#cb2-137" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**No physical losses.** The metrics here (PSNR/SSIM/LPIPS) are perceptual/photometric. They don't directly measure "did the restored image preserve the *temperature* signal at every pixel" — which is what a downstream physical task (fever screening, breath rate) actually cares about. The right thing to add for thermal SR specifically is a **temperature-preservation loss**: L1 between the restored and HR pixel intensities *in radiometric units* (after the iron-palette colormap inverse), weighted higher in the face region.</span>
<span id="cb2-138"><a href="#cb2-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a><span class="fu">## What's actually deployable today</span></span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a>If you have a Lepton-class thermal camera and want a real-time SR pipeline for a downstream face-aware task:</span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Use a classical CNN super-resolver** (EDSR/MSRN/A2N/DRLN). They all sit at PSNR 37, LPIPS 0.02 zero-shot.</span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Pick by downstream-task accuracy**, not perceptual sharpness. A2N had the best nostril-localisation accuracy in my test (0.7 px); DRLN had the best LPIPS. Test both on *your* downstream task before choosing.</span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Don't use a diffusion upscaler**. It looks sharper, breaks everything.</span>
<span id="cb2-146"><a href="#cb2-146" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**If you have ground-truth thermal data**, finetune the chosen classical CNN on it. That's what every PBVS TISR winner does.</span>
<span id="cb2-147"><a href="#cb2-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a><span class="fu">## Links</span></span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Experiment script: <span class="co">[</span><span class="ot">`posts/thermal-sr/scripts/run_super_res.py`</span><span class="co">](https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/run_super_res.py)</span></span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Companion thermal posts: <span class="co">[</span><span class="ot">Gemini thermal generation</span><span class="co">](2026-05-21-thermal-image-generation-gemini.qmd)</span> · <span class="co">[</span><span class="ot">thermal nostril series part 1</span><span class="co">](2026-05-20-thermal-nostril-bakeoff.qmd)</span></span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>PBVS Thermal Image SR Challenge: <span class="co">[</span><span class="ot">pbvs-workshop.github.io/challenge.html</span><span class="co">](https://pbvs-workshop.github.io/challenge.html)</span> · <span class="co">[</span><span class="ot">active Codabench leaderboard</span><span class="co">](https://www.codabench.org/competitions/12339/)</span></span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>PBVS 2025 winning solution (DRCT-L-X4): <span class="co">[</span><span class="ot">Raojiyong/PBVS_TSR</span><span class="co">](https://github.com/Raojiyong/PBVS_TSR)</span></span>
<span id="cb2-154"><a href="#cb2-154" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>PBVS 2024 2nd-place: <span class="co">[</span><span class="ot">upczww/TISR</span><span class="co">](https://github.com/upczww/TISR)</span></span>
<span id="cb2-155"><a href="#cb2-155" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Cross-spectral SR: <span class="co">[</span><span class="ot">SwinFuSR</span><span class="co">](https://arxiv.org/abs/2404.14533)</span></span>
<span id="cb2-156"><a href="#cb2-156" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Survey: <span class="co">[</span><span class="ot">Infrared Image SR Survey (yongsongH)</span><span class="co">](https://github.com/yongsongH/Infrared_Image_SR_Survey)</span></span>
<span id="cb2-157"><a href="#cb2-157" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Awesome Thermal SR list: <span class="co">[</span><span class="ot">zhgqcn/awesome-Thermal-Image-Super-Resolution</span><span class="co">](https://github.com/zhgqcn/awesome-Thermal-Image-Super-Resolution)</span></span>
<span id="cb2-158"><a href="#cb2-158" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Super-image package: <span class="co">[</span><span class="ot">eugenesiow/super-image</span><span class="co">](https://github.com/eugenesiow/super-image)</span></span>
<span id="cb2-159"><a href="#cb2-159" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Stable Diffusion x4 upscaler: <span class="co">[</span><span class="ot">stabilityai/stable-diffusion-x4-upscaler</span><span class="co">](https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Nipun Batra</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/nipunbatra">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>