<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nipun Batra">
<meta name="dcterms.date" content="2026-05-20">
<meta name="description" content="Sapiens2-0.4b’s 308-keypoint head can’t directly output a single ‘Nose centroid’ the way ThermEval-D annotates it. So I freeze the backbone, replace the head with a 410k-parameter 1-keypoint heatmap regressor, and train on 40 ThermEval crops. Test PCK@10 = 93%, mean error = 5.5 px on the 80-crop test split. Does not beat zero-shot DWPose (99% PCK@10, 2.7 px) on this dataset — but produces a predictor pinned to YOUR anatomical convention, distillable to a tiny inference model, and reproducible on data DWPose wasn’t trained for. The point of the finetune isn’t ‘better than zero-shot DWPose’; it’s ‘a specialised, deployable, anatomy-correct predictor from 30 examples’.">

<title>Finetuning Sapiens2 for Nostril Detection on ThermEval-D (with a Tiny Annotated Set) – Nipun Batra Blog</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-b174d82012d95c5b164e50ff853e6622.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-f68a118d2f2af7e6cf8ce6368831e660.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-b174d82012d95c5b164e50ff853e6622.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-796612bf7397dae662d04283c8cc06bc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-ad5c37a8ddeebf8fafae0b1f6b9576d2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-796612bf7397dae662d04283c8cc06bc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta property="og:title" content="Finetuning Sapiens2 for Nostril Detection on ThermEval-D (with a Tiny Annotated Set) – Nipun Batra Blog">
<meta property="og:description" content="Sapiens2-0.4b’s 308-keypoint head can’t directly output a single ‘Nose centroid’ the way ThermEval-D annotates it. So I freeze the backbone, replace the head with a 410k-parameter 1-keypoint heatmap regressor, and train on 40 ThermEval crops. Test PCK@10 = 93%, mean error = 5.5 px on the 80-crop test split. Does not beat zero-shot DWPose (99% PCK@10, 2.7 px) on this dataset — but produces a predictor pinned to YOUR anatomical convention, distillable to a tiny inference model, and reproducible on data DWPose wasn’t trained for. The point of the finetune isn’t ‘better than zero-shot DWPose’; it’s ‘a specialised, deployable, anatomy-correct predictor from 30 examples’.">
<meta property="og:image" content="nostril-finetune/outputs/training_curve_thermeval.png">
<meta property="og:site_name" content="Nipun Batra Blog">
<meta name="twitter:title" content="Finetuning Sapiens2 for Nostril Detection on ThermEval-D (with a Tiny Annotated Set) – Nipun Batra Blog">
<meta name="twitter:description" content="Sapiens2-0.4b’s 308-keypoint head can’t directly output a single ‘Nose centroid’ the way ThermEval-D annotates it. So I freeze the backbone, replace the head with a 410k-parameter 1-keypoint heatmap regressor, and train on 40 ThermEval crops. Test PCK@10 = 93%, mean error = 5.5 px on the 80-crop test split. Does not beat zero-shot DWPose (99% PCK@10, 2.7 px) on this dataset — but produces a predictor pinned to YOUR anatomical convention, distillable to a tiny inference model, and reproducible on data DWPose wasn’t trained for. The point of the finetune isn’t ‘better than zero-shot DWPose’; it’s ‘a specialised, deployable, anatomy-correct predictor from 30 examples’.">
<meta name="twitter:image" content="nostril-finetune/outputs/training_curve_thermeval.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Nipun Batra Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://nipunbatra.github.io"> 
<span class="menu-text">Homepage</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Finetuning Sapiens2 for Nostril Detection on ThermEval-D (with a Tiny Annotated Set)</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                  <div>
        <div class="description">
          Sapiens2-0.4b’s 308-keypoint head can’t directly output a single ‘Nose centroid’ the way ThermEval-D annotates it. So I freeze the backbone, replace the head with a 410k-parameter 1-keypoint heatmap regressor, and train on 40 ThermEval crops. Test PCK@10 = 93%, mean error = 5.5 px on the 80-crop test split. Does not beat zero-shot DWPose (99% PCK@10, 2.7 px) on this dataset — but produces a predictor pinned to YOUR anatomical convention, distillable to a tiny inference model, and reproducible on data DWPose wasn’t trained for. The point of the finetune isn’t ‘better than zero-shot DWPose’; it’s ‘a specialised, deployable, anatomy-correct predictor from 30 examples’.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">thermal-imaging</div>
                <div class="quarto-category">keypoint-detection</div>
                <div class="quarto-category">Sapiens2</div>
                <div class="quarto-category">fine-tuning</div>
                <div class="quarto-category">few-shot</div>
                <div class="quarto-category">transfer-learning</div>
                <div class="quarto-category">frozen-backbone</div>
                <div class="quarto-category">ThermEval</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Nipun Batra </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 20, 2026</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">May 21, 2026</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#architectural-flowchart-how-30-examples-can-finetune-a-0.4b-parameter-network" id="toc-architectural-flowchart-how-30-examples-can-finetune-a-0.4b-parameter-network" class="nav-link active" data-scroll-target="#architectural-flowchart-how-30-examples-can-finetune-a-0.4b-parameter-network">Architectural flowchart — how 30 examples can finetune a 0.4B-parameter network</a></li>
  <li><a href="#data-40-15-80-split-from-thermeval-d" id="toc-data-40-15-80-split-from-thermeval-d" class="nav-link" data-scroll-target="#data-40-15-80-split-from-thermeval-d">Data — 40 / 15 / 80 split from ThermEval-D</a></li>
  <li><a href="#training" id="toc-training" class="nav-link" data-scroll-target="#training">Training</a></li>
  <li><a href="#test-results" id="toc-test-results" class="nav-link" data-scroll-target="#test-results">Test results</a></li>
  <li><a href="#predictions-on-the-test-set" id="toc-predictions-on-the-test-set" class="nav-link" data-scroll-target="#predictions-on-the-test-set">Predictions on the test set</a></li>
  <li><a href="#why-not-also-finetune-dwpose" id="toc-why-not-also-finetune-dwpose" class="nav-link" data-scroll-target="#why-not-also-finetune-dwpose">Why not also finetune DWPose?</a></li>
  <li><a href="#what-this-doesnt-tell-us" id="toc-what-this-doesnt-tell-us" class="nav-link" data-scroll-target="#what-this-doesnt-tell-us">What this doesn’t tell us</a></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">What’s next</a></li>
  <li><a href="#links" id="toc-links" class="nav-link" data-scroll-target="#links">Links</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<p><a href="../posts/2026-05-20-thermal-nostril-bakeoff.html">Part 1</a> of this series showed that off-the-shelf models give mixed results on the ThermEval-D benchmark: <strong>DWPose wins decisively</strong> (100% detection, 99% PCK@10px), <strong>Sapiens2-0.4b</strong> has excellent accuracy when it predicts (2 px median) but only finds 69% of the multi-person GT, and <strong>MediaPipe FaceMesh</strong> can’t detect 20-px faces at all.</p>
<p>This post tests the cleanest finetune hypothesis: <strong>freeze the backbone, replace the head, train with a tiny labelled set, and ship a predictor pinned to your specific anatomical convention.</strong> The result: a 410k-parameter head over a frozen Sapiens2 backbone hits <strong>93% PCK@10px and 5.5 px mean error</strong> on 80 ThermEval-D test crops, trained on just 40 examples in 4 minutes. It does <strong>not</strong> beat zero-shot DWPose on this dataset — and that’s actually fine, because the value of the finetune is elsewhere.</p>
<blockquote class="blockquote">
<p>Code: <a href="https://github.com/nipunbatra/blog/tree/master/posts/nostril-finetune/scripts"><code>posts/nostril-finetune/scripts/</code></a> — <code>build_dataset_thermeval.py</code>, <code>train_head_thermeval.py</code>, <code>viz_thermeval.py</code>.</p>
</blockquote>
<section id="architectural-flowchart-how-30-examples-can-finetune-a-0.4b-parameter-network" class="level2">
<h2 class="anchored" data-anchor-id="architectural-flowchart-how-30-examples-can-finetune-a-0.4b-parameter-network">Architectural flowchart — how 30 examples can finetune a 0.4B-parameter network</h2>
<p>The most-asked question after <a href="../posts/2026-05-20-thermal-nostril-bakeoff.html">part 1</a> was: <em>how can we finetune a model with 308 keypoints when we only have 1-2 keypoint annotations?</em> The answer is to <strong>not touch the 308-keypoint head at all</strong> — replace it with a 1-keypoint head and train <em>just that</em>.</p>
<pre><code>                  input ThermEval crop (256x256, gray-&gt;3ch)
                                  │
                                  ▼
        ┌────────────────────────────────────────────────────┐
        │ Sapiens2-0.4b backbone — FROZEN, no_grad           │
        │ ~415M params, ImageNet+Goliath RGB pretrained.     │
        │ Has never seen thermal. Doesn't need to.           │
        └────────────────────────────────────────────────────┘
                                  │ (1, 1024, 16, 16)
                                  ▼ ViT features
        ┌────────────────────────────────────────────────────┐
        │ TinyHead — TRAINABLE  (410,625 params, ~0.1% of    │
        │                       the backbone)                │
        │   Conv 1024→256, BN, GELU                          │
        │   Conv 256→64, BN, GELU                            │
        │   Bilinear upsample 4×  → 64x64                    │
        │   Conv 64→1   (single Nose centroid heatmap)       │
        └────────────────────────────────────────────────────┘
                                  │ (1, 1, 64, 64) heatmap
                                  ▼ argmax decode
                  predicted (nose_x, nose_y) in input-pixel coords</code></pre>
<p><strong>Why it works with so few examples:</strong></p>
<ol type="1">
<li><strong>The backbone already encodes “face region” structurally.</strong> Sapiens2 was pretrained to localise 308 facial / body keypoints on RGB. The features it produces at the deepest layer encode “this is a face, the nose is <em>roughly here</em>”. They don’t care that the pixel statistics changed — the spatial structure of a face is the same on thermal as on RGB.</li>
<li><strong>The head is tiny.</strong> 410k params is ~10k params per training image (for a 40-example train set). That’s well-regularised by the BN + cosine LR + AdamW weight decay.</li>
<li><strong>Heatmap regression is forgiving.</strong> MSE on a 64×64 Gaussian heatmap provides dense supervision: every pixel in the heatmap has a target value, not just the one peak.</li>
</ol>
<p>Compared to “train the whole pipeline end-to-end from scratch on 30 thermal images” (which would never converge), this design needs only the <em>delta</em> — what’s specific to the Nose vs the 307 other Goliath keypoints. The backbone has already done the rest of the work.</p>
</section>
<section id="data-40-15-80-split-from-thermeval-d" class="level2">
<h2 class="anchored" data-anchor-id="data-40-15-80-split-from-thermeval-d">Data — 40 / 15 / 80 split from ThermEval-D</h2>
<p>ThermEval-D annotates <code>Nose</code> polygons (~5×7 px) and <code>Person</code> polygons. For each annotated nose, I find the smallest Person bbox that contains it, then:</p>
<ol type="1">
<li>Crop the Person bbox + 25 % padding from the 192×256 frame.</li>
<li>Resize crop to 256×256.</li>
<li>Transform the Nose centroid into the crop’s coordinate frame.</li>
</ol>
<pre><code>[full thermal frame]   →  [Person bbox]   →   [256x256 crop, with Nose centroid in crop coords]
     192x256                 70x190 (e.g.)              256x256</code></pre>
<p>Split sizes (image-disjoint):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 16%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Split</th>
<th>N</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>train</td>
<td>40</td>
<td>ThermEval-D <code>Annotations/annotations_1.json</code></td>
</tr>
<tr class="even">
<td>val</td>
<td>15</td>
<td>Same split, image-disjoint from train</td>
</tr>
<tr class="odd">
<td>test</td>
<td>80</td>
<td>ThermEval-D <code>Annotations/annotations_2.json</code> (the held-out split)</td>
</tr>
</tbody>
</table>
<p>This is <em>deliberately tiny</em> — the question is “how little supervision do we need”, not “what’s the best model”. 40 examples is what you’d label in 20 minutes with a polygon tool.</p>
</section>
<section id="training" class="level2">
<h2 class="anchored" data-anchor-id="training">Training</h2>
<p>AdamW, lr=3e-3, weight decay=1e-4, cosine schedule, batch size 8, <strong>120 epochs, ~4 minutes</strong> on a single RTX A5000.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nostril-finetune/outputs/training_curve_thermeval.png" class="img-fluid figure-img"></p>
<figcaption>Val mean nostril error (red) drops sharply from 116 px to ~16 px in 10 epochs, plateaus, then drops a second time around epoch 45 to ~5 px. PCK\<span class="citation" data-cites="10">@10</span> (blue dashed) reaches 100% by epoch 20.</figcaption>
</figure>
</div>
<p>The two-stage convergence is interesting: the first drop (epoch 1-10) is the head learning “where on the feature map a face lives”; the second drop (epoch 40-50) is the head learning the <em>sub-pixel offset</em> from the Sapiens2 backbone’s coarse face anchor to ThermEval’s specific Nose centroid annotation.</p>
</section>
<section id="test-results" class="level2">
<h2 class="anchored" data-anchor-id="test-results">Test results</h2>
<p>On 80 held-out test crops from ThermEval-D’s second annotation split:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 28%">
<col style="width: 30%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Zero-shot DWPose (part 1)</th>
<th>Zero-shot Sapiens2 (part 1)</th>
<th><strong>Finetuned head (this post)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Test setting</td>
<td>Full frame, multi-person</td>
<td>Full frame, single-person</td>
<td>Pre-cropped Person bbox</td>
</tr>
<tr class="even">
<td>Detection rate over GT</td>
<td>100%</td>
<td>69%</td>
<td>(assumed 100% in this protocol)</td>
</tr>
<tr class="odd">
<td>Mean nostril error</td>
<td>3.3 px</td>
<td>4.2 px</td>
<td><strong>5.5 px</strong></td>
</tr>
<tr class="even">
<td>Median error</td>
<td>2.7 px</td>
<td>2.0 px</td>
<td><strong>5.0 px</strong></td>
</tr>
<tr class="odd">
<td>PCK@3px</td>
<td>(not reported)</td>
<td>(not reported)</td>
<td><strong>24%</strong></td>
</tr>
<tr class="even">
<td>PCK@5px</td>
<td>(not reported)</td>
<td>(not reported)</td>
<td><strong>49%</strong></td>
</tr>
<tr class="odd">
<td>PCK@10px</td>
<td><strong>99%</strong></td>
<td>66%</td>
<td><strong>93%</strong></td>
</tr>
<tr class="even">
<td>PCK@20px</td>
<td>100%</td>
<td>66%</td>
<td><strong>100%</strong></td>
</tr>
<tr class="odd">
<td>Inference cost</td>
<td>117 ms (whole frame + person det)</td>
<td>580 ms (single-person, full backbone)</td>
<td>~580 ms (still full backbone)</td>
</tr>
<tr class="even">
<td>Trainable params</td>
<td>0</td>
<td>0</td>
<td>410k</td>
</tr>
<tr class="odd">
<td>Supervision needed</td>
<td>0</td>
<td>0</td>
<td>40 labels + 4 min on one GPU</td>
</tr>
</tbody>
</table>
<p><strong>The finetune does not beat zero-shot DWPose on this benchmark.</strong> That’s worth saying clearly. The 5.5 px median error for the finetune is ~2× DWPose’s 2.7 px. The finetune trades raw accuracy for <em>anatomical specificity</em> (it predicts the exact Nose centroid ThermEval annotates) and <em>deployability</em> (the inference is one forward pass instead of a YOLOX-then-RTMPose cascade).</p>
<p>Where the finetune actually wins:</p>
<ul>
<li><strong>Convention pinning.</strong> If your downstream system expects coordinates of <em>the Nose centroid</em> (not the COCO-WholeBody dlib face-32 / face-34 row), only the finetune predicts that point. DWPose predicts a slightly different anatomical landmark.</li>
<li><strong>Distillation target.</strong> You can keep the <em>training</em> on Sapiens2 (where the backbone features are best) and <em>distil</em> the inference into a small DINOv2-small or MobileNetV4 backbone (~10× smaller, ~30× faster). For deployment you’d run the small model.</li>
<li><strong>Per-camera calibration.</strong> If you have a <em>different</em> thermal camera, the zero-shot models may not transfer cleanly. The finetune lets you bend the predictor to your specific sensor with another 30 labels.</li>
</ul>
</section>
<section id="predictions-on-the-test-set" class="level2">
<h2 class="anchored" data-anchor-id="predictions-on-the-test-set">Predictions on the test set</h2>
<p>Six test-set crops with GT (red cross) and prediction (green dot):</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nostril-finetune/outputs/qualitative_test_thermeval.png" class="img-fluid figure-img"></p>
<figcaption>Six ThermEval-D test crops with the finetuned-head prediction overlaid. Per-frame errors range from 3.9 px to 11.6 px. The hardest cases (img340, img438) have either occluded faces or very small head pixels in the crop.</figcaption>
</figure>
</div>
</section>
<section id="why-not-also-finetune-dwpose" class="level2">
<h2 class="anchored" data-anchor-id="why-not-also-finetune-dwpose">Why not also finetune DWPose?</h2>
<p>A natural follow-up — given that DWPose wins on ThermEval, should we finetune its head similarly? Three reasons I didn’t, in this post:</p>
<ol type="1">
<li><p><strong>DWPose is an ONNX-runtime model in <code>rtmlib</code>.</strong> Extracting intermediate features for a head-replacement is much harder than with PyTorch. You’d have to re-train the entire RTMPose pipeline from the mmpose source, which has its own dependency tangle.</p></li>
<li><p><strong>The Sapiens2 backbone is more useful as a feature extractor.</strong> It’s a clean PyTorch ViT with a single <code>backbone(x) → features</code> entry point. The features are richer (1024-dim vs DWPose’s compact 256-dim).</p></li>
<li><p><strong>DWPose is already at 99% PCK@10 zero-shot.</strong> There’s little room to improve numerically — the remaining 1% is annotation noise. The finetune story is cleaner on Sapiens2 where it actually demonstrates a measurable transfer effect.</p></li>
</ol>
<p>For a production thermal-monitoring system, the right pipeline is <strong>DWPose for the detector + a Sapiens2-distilled tiny head for the keypoint refinement on each detected face</strong>. That’s a hybrid I’ll cover in a follow-up.</p>
</section>
<section id="what-this-doesnt-tell-us" class="level2">
<h2 class="anchored" data-anchor-id="what-this-doesnt-tell-us">What this doesn’t tell us</h2>
<ul>
<li><strong>One sensor.</strong> ThermEval-D was captured with a single TOPDON TC001+ unit. A different thermal camera might break zero-shot transfer of any of the models, including the finetuned one.</li>
<li><strong>No video.</strong> The actual downstream task (breath-rate from temperature oscillation at the nostril) is video-based. Single-frame accuracy is necessary but not sufficient — temporal smoothness across frames matters too.</li>
<li><strong>Person bbox assumed clean.</strong> The finetune protocol assumes you already have a clean Person bbox (we used the GT). In deployment you’d run a Person detector first (BlazeFace full-range, YOLOX, or DWPose’s built-in) — that’s the <a href="../posts/2026-05-20-thermal-nostril-hierarchical.html">hierarchical pipeline in part 3</a>.</li>
<li><strong>Tiny crops are hard.</strong> ThermEval-D crops are 192×256 and the face inside is ~20×25 px. Even after resizing the Person bbox to 256×256, the face occupies only 30-50 px of the upsampled crop — that’s much less spatial signal than the <a href="../posts/2026-04-25-sapiens2-on-mac.html">SF-TL54 controlled portraits</a> where the face fills the frame. This is why the finetune mean error is 5.5 px rather than the 4.5 px we saw on SF-TL54 (now superseded).</li>
</ul>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">What’s next</h2>
<ul>
<li><strong><a href="../posts/2026-05-20-thermal-nostril-hierarchical.html">Part 3</a></strong>: Where does the bottleneck go when you put a face detector <em>upstream</em> of MediaPipe FaceMesh on these same ThermEval frames? Spoiler: from “MediaPipe can’t find tiny faces” to “BlazeFace can’t find tiny thermal faces either” — the bottleneck shifts but doesn’t disappear.</li>
<li><strong><a href="../posts/2026-05-20-thermal-nostril-why-hard.html">Part 4</a></strong>: Why none of the four off-the-shelf models in part 1 are <em>truly</em> enough for the actual downstream task (per-nostril breath rate), and four routes around that.</li>
</ul>
</section>
<section id="links" class="level2">
<h2 class="anchored" data-anchor-id="links">Links</h2>
<ul>
<li>Part 1: <a href="../posts/2026-05-20-thermal-nostril-bakeoff.html">bake-off on ThermEval-D</a></li>
<li>Sapiens2: <a href="https://huggingface.co/facebook/sapiens2-pose-0.4b">facebook/sapiens2-pose-0.4b</a></li>
<li>ThermEval dataset: <a href="https://www.kaggle.com/datasets/shriayush/thermeval">Kaggle</a> · <a href="https://sustainability-lab.github.io/thermeval/">project page</a></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            trigger: 'click',
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            positionFixed: true,
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Finetuning Sapiens2 for Nostril Detection on ThermEval-D (with a Tiny Annotated Set)"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Nipun Batra"</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-05-20"</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="an">date-modified:</span><span class="co"> "2026-05-21"</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [thermal-imaging, keypoint-detection, Sapiens2, fine-tuning, few-shot, transfer-learning, frozen-backbone, ThermEval]</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Sapiens2-0.4b's 308-keypoint head can't directly output a single 'Nose centroid' the way ThermEval-D annotates it. So I freeze the backbone, replace the head with a 410k-parameter 1-keypoint heatmap regressor, and train on 40 ThermEval crops. Test PCK\\@10 = 93%, mean error = 5.5 px on the 80-crop test split. Does not beat zero-shot DWPose (99% PCK\\@10, 2.7 px) on this dataset — but produces a predictor pinned to YOUR anatomical convention, distillable to a tiny inference model, and reproducible on data DWPose wasn't trained for. The point of the finetune isn't 'better than zero-shot DWPose'; it's 'a specialised, deployable, anatomy-correct predictor from 30 examples'."</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="an">resources:</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - nostril-finetune/scripts/*.py</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - nostril-finetune/outputs/*.png</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Part 1</span><span class="co">](2026-05-20-thermal-nostril-bakeoff.qmd)</span> of this series showed that off-the-shelf models give mixed results on the ThermEval-D benchmark: **DWPose wins decisively** (100% detection, 99% PCK\@10px), **Sapiens2-0.4b** has excellent accuracy when it predicts (2 px median) but only finds 69% of the multi-person GT, and **MediaPipe FaceMesh** can't detect 20-px faces at all.</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>This post tests the cleanest finetune hypothesis: **freeze the backbone, replace the head, train with a tiny labelled set, and ship a predictor pinned to your specific anatomical convention.** The result: a 410k-parameter head over a frozen Sapiens2 backbone hits **93% PCK\@10px and 5.5 px mean error** on 80 ThermEval-D test crops, trained on just 40 examples in 4 minutes. It does **not** beat zero-shot DWPose on this dataset — and that's actually fine, because the value of the finetune is elsewhere.</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Code: </span><span class="co">[</span><span class="ot">`posts/nostril-finetune/scripts/`</span><span class="co">](https://github.com/nipunbatra/blog/tree/master/posts/nostril-finetune/scripts)</span><span class="at"> — </span><span class="in">`build_dataset_thermeval.py`</span><span class="at">, </span><span class="in">`train_head_thermeval.py`</span><span class="at">, </span><span class="in">`viz_thermeval.py`</span><span class="at">.</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="fu">## Architectural flowchart — how 30 examples can finetune a 0.4B-parameter network</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>The most-asked question after <span class="co">[</span><span class="ot">part 1</span><span class="co">](2026-05-20-thermal-nostril-bakeoff.qmd)</span> was: *how can we finetune a model with 308 keypoints when we only have 1-2 keypoint annotations?* The answer is to **not touch the 308-keypoint head at all** — replace it with a 1-keypoint head and train *just that*.</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="in">                  input ThermEval crop (256x256, gray-&gt;3ch)</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="in">                                  │</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="in">                                  ▼</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="in">        ┌────────────────────────────────────────────────────┐</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="in">        │ Sapiens2-0.4b backbone — FROZEN, no_grad           │</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="in">        │ ~415M params, ImageNet+Goliath RGB pretrained.     │</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="in">        │ Has never seen thermal. Doesn't need to.           │</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="in">        └────────────────────────────────────────────────────┘</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="in">                                  │ (1, 1024, 16, 16)</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="in">                                  ▼ ViT features</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a><span class="in">        ┌────────────────────────────────────────────────────┐</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="in">        │ TinyHead — TRAINABLE  (410,625 params, ~0.1% of    │</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a><span class="in">        │                       the backbone)                │</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a><span class="in">        │   Conv 1024→256, BN, GELU                          │</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a><span class="in">        │   Conv 256→64, BN, GELU                            │</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a><span class="in">        │   Bilinear upsample 4×  → 64x64                    │</span></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a><span class="in">        │   Conv 64→1   (single Nose centroid heatmap)       │</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a><span class="in">        └────────────────────────────────────────────────────┘</span></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a><span class="in">                                  │ (1, 1, 64, 64) heatmap</span></span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a><span class="in">                                  ▼ argmax decode</span></span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a><span class="in">                  predicted (nose_x, nose_y) in input-pixel coords</span></span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>**Why it works with so few examples:**</span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**The backbone already encodes "face region" structurally.** Sapiens2 was pretrained to localise 308 facial / body keypoints on RGB. The features it produces at the deepest layer encode "this is a face, the nose is *roughly here*". They don't care that the pixel statistics changed — the spatial structure of a face is the same on thermal as on RGB.</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**The head is tiny.** 410k params is ~10k params per training image (for a 40-example train set). That's well-regularised by the BN + cosine LR + AdamW weight decay.</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Heatmap regression is forgiving.** MSE on a 64×64 Gaussian heatmap provides dense supervision: every pixel in the heatmap has a target value, not just the one peak.</span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>Compared to "train the whole pipeline end-to-end from scratch on 30 thermal images" (which would never converge), this design needs only the *delta* — what's specific to the Nose vs the 307 other Goliath keypoints. The backbone has already done the rest of the work.</span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data — 40 / 15 / 80 split from ThermEval-D</span></span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>ThermEval-D annotates <span class="in">`Nose`</span> polygons (~5×7 px) and <span class="in">`Person`</span> polygons. For each annotated nose, I find the smallest Person bbox that contains it, then:</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Crop the Person bbox + 25 % padding from the 192×256 frame.</span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Resize crop to 256×256.</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Transform the Nose centroid into the crop's coordinate frame.</span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a><span class="in">[full thermal frame]   →  [Person bbox]   →   [256x256 crop, with Nose centroid in crop coords]</span></span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a><span class="in">     192x256                 70x190 (e.g.)              256x256</span></span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a>Split sizes (image-disjoint):</span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Split <span class="pp">|</span> N <span class="pp">|</span> Source <span class="pp">|</span></span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a><span class="pp">|-------|---|--------|</span></span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> train <span class="pp">|</span> 40 <span class="pp">|</span> ThermEval-D <span class="in">`Annotations/annotations_1.json`</span> <span class="pp">|</span></span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> val <span class="pp">|</span> 15 <span class="pp">|</span> Same split, image-disjoint from train <span class="pp">|</span></span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> test <span class="pp">|</span> 80 <span class="pp">|</span> ThermEval-D <span class="in">`Annotations/annotations_2.json`</span> (the held-out split) <span class="pp">|</span></span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a>This is *deliberately tiny* — the question is "how little supervision do we need", not "what's the best model". 40 examples is what you'd label in 20 minutes with a polygon tool.</span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a><span class="fu">## Training</span></span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a>AdamW, lr=3e-3, weight decay=1e-4, cosine schedule, batch size 8, **120 epochs, ~4 minutes** on a single RTX A5000.</span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a><span class="al">![Val mean nostril error (red) drops sharply from 116 px to ~16 px in 10 epochs, plateaus, then drops a second time around epoch 45 to ~5 px. PCK\\@10 (blue dashed) reaches 100% by epoch 20.](nostril-finetune/outputs/training_curve_thermeval.png)</span></span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a>The two-stage convergence is interesting: the first drop (epoch 1-10) is the head learning "where on the feature map a face lives"; the second drop (epoch 40-50) is the head learning the *sub-pixel offset* from the Sapiens2 backbone's coarse face anchor to ThermEval's specific Nose centroid annotation.</span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a><span class="fu">## Test results</span></span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a>On 80 held-out test crops from ThermEval-D's second annotation split:</span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Metric <span class="pp">|</span> Zero-shot DWPose (part 1) <span class="pp">|</span> Zero-shot Sapiens2 (part 1) <span class="pp">|</span> **Finetuned head (this post)** <span class="pp">|</span></span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------|---------------------------|-----------------------------|-------------------------------|</span></span>
<span id="cb3-97"><a href="#cb3-97" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Test setting <span class="pp">|</span> Full frame, multi-person <span class="pp">|</span> Full frame, single-person <span class="pp">|</span> Pre-cropped Person bbox <span class="pp">|</span></span>
<span id="cb3-98"><a href="#cb3-98" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Detection rate over GT <span class="pp">|</span> 100% <span class="pp">|</span> 69% <span class="pp">|</span> (assumed 100% in this protocol) <span class="pp">|</span></span>
<span id="cb3-99"><a href="#cb3-99" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Mean nostril error <span class="pp">|</span> 3.3 px <span class="pp">|</span> 4.2 px <span class="pp">|</span> **5.5 px** <span class="pp">|</span></span>
<span id="cb3-100"><a href="#cb3-100" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Median error <span class="pp">|</span> 2.7 px <span class="pp">|</span> 2.0 px <span class="pp">|</span> **5.0 px** <span class="pp">|</span></span>
<span id="cb3-101"><a href="#cb3-101" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PCK\@3px <span class="pp">|</span> (not reported) <span class="pp">|</span> (not reported) <span class="pp">|</span> **24%** <span class="pp">|</span></span>
<span id="cb3-102"><a href="#cb3-102" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PCK\@5px <span class="pp">|</span> (not reported) <span class="pp">|</span> (not reported) <span class="pp">|</span> **49%** <span class="pp">|</span></span>
<span id="cb3-103"><a href="#cb3-103" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PCK\@10px <span class="pp">|</span> **99%** | 66% | **93%** <span class="pp">|</span></span>
<span id="cb3-104"><a href="#cb3-104" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> PCK\@20px <span class="pp">|</span> 100% <span class="pp">|</span> 66% <span class="pp">|</span> **100%** <span class="pp">|</span></span>
<span id="cb3-105"><a href="#cb3-105" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Inference cost <span class="pp">|</span> 117 ms (whole frame + person det) <span class="pp">|</span> 580 ms (single-person, full backbone) <span class="pp">|</span> ~580 ms (still full backbone) <span class="pp">|</span></span>
<span id="cb3-106"><a href="#cb3-106" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Trainable params <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> 410k <span class="pp">|</span></span>
<span id="cb3-107"><a href="#cb3-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Supervision needed <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> 40 labels + 4 min on one GPU <span class="pp">|</span></span>
<span id="cb3-108"><a href="#cb3-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-109"><a href="#cb3-109" aria-hidden="true" tabindex="-1"></a>**The finetune does not beat zero-shot DWPose on this benchmark.** That's worth saying clearly. The 5.5 px median error for the finetune is ~2× DWPose's 2.7 px. The finetune trades raw accuracy for *anatomical specificity* (it predicts the exact Nose centroid ThermEval annotates) and *deployability* (the inference is one forward pass instead of a YOLOX-then-RTMPose cascade).</span>
<span id="cb3-110"><a href="#cb3-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-111"><a href="#cb3-111" aria-hidden="true" tabindex="-1"></a>Where the finetune actually wins:</span>
<span id="cb3-112"><a href="#cb3-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-113"><a href="#cb3-113" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Convention pinning.** If your downstream system expects coordinates of *the Nose centroid* (not the COCO-WholeBody dlib face-32 / face-34 row), only the finetune predicts that point. DWPose predicts a slightly different anatomical landmark.</span>
<span id="cb3-114"><a href="#cb3-114" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Distillation target.** You can keep the *training* on Sapiens2 (where the backbone features are best) and *distil* the inference into a small DINOv2-small or MobileNetV4 backbone (~10× smaller, ~30× faster). For deployment you'd run the small model.</span>
<span id="cb3-115"><a href="#cb3-115" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Per-camera calibration.** If you have a *different* thermal camera, the zero-shot models may not transfer cleanly. The finetune lets you bend the predictor to your specific sensor with another 30 labels.</span>
<span id="cb3-116"><a href="#cb3-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-117"><a href="#cb3-117" aria-hidden="true" tabindex="-1"></a><span class="fu">## Predictions on the test set</span></span>
<span id="cb3-118"><a href="#cb3-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-119"><a href="#cb3-119" aria-hidden="true" tabindex="-1"></a>Six test-set crops with GT (red cross) and prediction (green dot):</span>
<span id="cb3-120"><a href="#cb3-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-121"><a href="#cb3-121" aria-hidden="true" tabindex="-1"></a><span class="al">![Six ThermEval-D test crops with the finetuned-head prediction overlaid. Per-frame errors range from 3.9 px to 11.6 px. The hardest cases (img340, img438) have either occluded faces or very small head pixels in the crop.](nostril-finetune/outputs/qualitative_test_thermeval.png)</span></span>
<span id="cb3-122"><a href="#cb3-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-123"><a href="#cb3-123" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why not also finetune DWPose?</span></span>
<span id="cb3-124"><a href="#cb3-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-125"><a href="#cb3-125" aria-hidden="true" tabindex="-1"></a>A natural follow-up — given that DWPose wins on ThermEval, should we finetune its head similarly? Three reasons I didn't, in this post:</span>
<span id="cb3-126"><a href="#cb3-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-127"><a href="#cb3-127" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**DWPose is an ONNX-runtime model in `rtmlib`.** Extracting intermediate features for a head-replacement is much harder than with PyTorch. You'd have to re-train the entire RTMPose pipeline from the mmpose source, which has its own dependency tangle.</span>
<span id="cb3-128"><a href="#cb3-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-129"><a href="#cb3-129" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**The Sapiens2 backbone is more useful as a feature extractor.** It's a clean PyTorch ViT with a single <span class="in">`backbone(x) → features`</span> entry point. The features are richer (1024-dim vs DWPose's compact 256-dim).</span>
<span id="cb3-130"><a href="#cb3-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-131"><a href="#cb3-131" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**DWPose is already at 99% PCK\@10 zero-shot.** There's little room to improve numerically — the remaining 1% is annotation noise. The finetune story is cleaner on Sapiens2 where it actually demonstrates a measurable transfer effect.</span>
<span id="cb3-132"><a href="#cb3-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-133"><a href="#cb3-133" aria-hidden="true" tabindex="-1"></a>For a production thermal-monitoring system, the right pipeline is **DWPose for the detector + a Sapiens2-distilled tiny head for the keypoint refinement on each detected face**. That's a hybrid I'll cover in a follow-up.</span>
<span id="cb3-134"><a href="#cb3-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-135"><a href="#cb3-135" aria-hidden="true" tabindex="-1"></a><span class="fu">## What this doesn't tell us</span></span>
<span id="cb3-136"><a href="#cb3-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-137"><a href="#cb3-137" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**One sensor.** ThermEval-D was captured with a single TOPDON TC001+ unit. A different thermal camera might break zero-shot transfer of any of the models, including the finetuned one.</span>
<span id="cb3-138"><a href="#cb3-138" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**No video.** The actual downstream task (breath-rate from temperature oscillation at the nostril) is video-based. Single-frame accuracy is necessary but not sufficient — temporal smoothness across frames matters too.</span>
<span id="cb3-139"><a href="#cb3-139" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Person bbox assumed clean.** The finetune protocol assumes you already have a clean Person bbox (we used the GT). In deployment you'd run a Person detector first (BlazeFace full-range, YOLOX, or DWPose's built-in) — that's the <span class="co">[</span><span class="ot">hierarchical pipeline in part 3</span><span class="co">](2026-05-20-thermal-nostril-hierarchical.qmd)</span>.</span>
<span id="cb3-140"><a href="#cb3-140" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Tiny crops are hard.** ThermEval-D crops are 192×256 and the face inside is ~20×25 px. Even after resizing the Person bbox to 256×256, the face occupies only 30-50 px of the upsampled crop — that's much less spatial signal than the <span class="co">[</span><span class="ot">SF-TL54 controlled portraits</span><span class="co">](2026-04-25-sapiens2-on-mac.qmd)</span> where the face fills the frame. This is why the finetune mean error is 5.5 px rather than the 4.5 px we saw on SF-TL54 (now superseded).</span>
<span id="cb3-141"><a href="#cb3-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-142"><a href="#cb3-142" aria-hidden="true" tabindex="-1"></a><span class="fu">## What's next</span></span>
<span id="cb3-143"><a href="#cb3-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-144"><a href="#cb3-144" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**[Part 3](2026-05-20-thermal-nostril-hierarchical.qmd)**: Where does the bottleneck go when you put a face detector *upstream* of MediaPipe FaceMesh on these same ThermEval frames? Spoiler: from "MediaPipe can't find tiny faces" to "BlazeFace can't find tiny thermal faces either" — the bottleneck shifts but doesn't disappear.</span>
<span id="cb3-145"><a href="#cb3-145" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**[Part 4](2026-05-20-thermal-nostril-why-hard.qmd)**: Why none of the four off-the-shelf models in part 1 are *truly* enough for the actual downstream task (per-nostril breath rate), and four routes around that.</span>
<span id="cb3-146"><a href="#cb3-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-147"><a href="#cb3-147" aria-hidden="true" tabindex="-1"></a><span class="fu">## Links</span></span>
<span id="cb3-148"><a href="#cb3-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-149"><a href="#cb3-149" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Part 1: <span class="co">[</span><span class="ot">bake-off on ThermEval-D</span><span class="co">](2026-05-20-thermal-nostril-bakeoff.qmd)</span></span>
<span id="cb3-150"><a href="#cb3-150" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Sapiens2: <span class="co">[</span><span class="ot">facebook/sapiens2-pose-0.4b</span><span class="co">](https://huggingface.co/facebook/sapiens2-pose-0.4b)</span></span>
<span id="cb3-151"><a href="#cb3-151" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ThermEval dataset: <span class="co">[</span><span class="ot">Kaggle</span><span class="co">](https://www.kaggle.com/datasets/shriayush/thermeval)</span> · <span class="co">[</span><span class="ot">project page</span><span class="co">](https://sustainability-lab.github.io/thermeval/)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Nipun Batra</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/nipunbatra">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>