<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nipun Batra">
<meta name="dcterms.date" content="2026-05-22">
<meta name="description" content="Follow-up to the zero-shot thermal SR post. Take DRLN (the best classical-CNN super-resolver in the zero-shot bake-off), pre-loaded with RGB-pretrained weights, finetune for 60 epochs on 831 thermal HR-LR pairs from SF-TL54 + ThermEval-D combined. Result: val PSNR climbs from 36.39 (zero-shot) to 38.60 (finetuned), +2.21 dB. Per-dataset breakdown shows SF-TL54 portraits gain +2.76 dB and ThermEval-D scenes gain +1.77 dB — finetuning helps more on the in-distribution images. The honest paper-grade nuance: PSNR/SSIM/LPIPS all improve materially, but the downstream nostril-localisation error is essentially unchanged. PSNR-optimised SR doesn’t automatically translate to downstream-task accuracy.">

<title>Finetuning DRLN for Thermal Super-Resolution — A Multi-Dataset PBVS-Style Submission – Nipun Batra Blog</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-577833abe1b92350236646abf7bf8d21.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-82e37cb7b6434006901e7fa82e7d06ec.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-577833abe1b92350236646abf7bf8d21.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9482772de5f96bc669c49da57733e8fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-ba0ea52c466f323bb4a80d9892c7c8cb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-9482772de5f96bc669c49da57733e8fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta property="og:title" content="Finetuning DRLN for Thermal Super-Resolution — A Multi-Dataset PBVS-Style Submission – Nipun Batra Blog">
<meta property="og:description" content="Follow-up to the zero-shot thermal SR post. Take DRLN (the best classical-CNN super-resolver in the zero-shot bake-off), pre-loaded with RGB-pretrained weights, finetune for 60 epochs on 831 thermal HR-LR pairs from SF-TL54 + ThermEval-D combined. Result: val PSNR climbs from 36.39 (zero-shot) to 38.60 (finetuned), +2.21 dB. Per-dataset breakdown shows SF-TL54 portraits gain +2.76 dB and ThermEval-D scenes gain +1.77 dB — finetuning helps more on the in-distribution images. The honest paper-grade nuance: PSNR/SSIM/LPIPS all improve materially, but the downstream nostril-localisation error is essentially unchanged. PSNR-optimised SR doesn’t automatically translate to downstream-task accuracy.">
<meta property="og:image" content="thermal-sr/outputs/ft_history_curve.png">
<meta property="og:site_name" content="Nipun Batra Blog">
<meta name="twitter:title" content="Finetuning DRLN for Thermal Super-Resolution — A Multi-Dataset PBVS-Style Submission – Nipun Batra Blog">
<meta name="twitter:description" content="Follow-up to the zero-shot thermal SR post. Take DRLN (the best classical-CNN super-resolver in the zero-shot bake-off), pre-loaded with RGB-pretrained weights, finetune for 60 epochs on 831 thermal HR-LR pairs from SF-TL54 + ThermEval-D combined. Result: val PSNR climbs from 36.39 (zero-shot) to 38.60 (finetuned), +2.21 dB. Per-dataset breakdown shows SF-TL54 portraits gain +2.76 dB and ThermEval-D scenes gain +1.77 dB — finetuning helps more on the in-distribution images. The honest paper-grade nuance: PSNR/SSIM/LPIPS all improve materially, but the downstream nostril-localisation error is essentially unchanged. PSNR-optimised SR doesn’t automatically translate to downstream-task accuracy.">
<meta name="twitter:image" content="thermal-sr/outputs/ft_history_curve.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Nipun Batra Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://nipunbatra.github.io"> 
<span class="menu-text">Homepage</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Finetuning DRLN for Thermal Super-Resolution — A Multi-Dataset PBVS-Style Submission</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                  <div>
        <div class="description">
          Follow-up to the zero-shot thermal SR post. Take DRLN (the best classical-CNN super-resolver in the zero-shot bake-off), pre-loaded with RGB-pretrained weights, finetune for 60 epochs on 831 thermal HR-LR pairs from SF-TL54 + ThermEval-D combined. Result: val PSNR climbs from 36.39 (zero-shot) to 38.60 (finetuned), +2.21 dB. Per-dataset breakdown shows SF-TL54 portraits gain +2.76 dB and ThermEval-D scenes gain +1.77 dB — finetuning helps more on the in-distribution images. The honest paper-grade nuance: PSNR/SSIM/LPIPS all improve materially, but the downstream nostril-localisation error is essentially unchanged. PSNR-optimised SR doesn’t automatically translate to downstream-task accuracy.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">thermal-imaging</div>
                <div class="quarto-category">super-resolution</div>
                <div class="quarto-category">DRLN</div>
                <div class="quarto-category">fine-tuning</div>
                <div class="quarto-category">multi-dataset</div>
                <div class="quarto-category">PBVS</div>
                <div class="quarto-category">paper-prototype</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Nipun Batra </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 22, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#recap" id="toc-recap" class="nav-link active" data-scroll-target="#recap">Recap</a></li>
  <li><a href="#multi-dataset-thermal-sr-training-set" id="toc-multi-dataset-thermal-sr-training-set" class="nav-link" data-scroll-target="#multi-dataset-thermal-sr-training-set">Multi-dataset thermal SR training set</a></li>
  <li><a href="#finetune-protocol" id="toc-finetune-protocol" class="nav-link" data-scroll-target="#finetune-protocol">Finetune protocol</a></li>
  <li><a href="#training-curve" id="toc-training-curve" class="nav-link" data-scroll-target="#training-curve">Training curve</a></li>
  <li><a href="#test-results-zero-shot-vs-finetuned-per-dataset" id="toc-test-results-zero-shot-vs-finetuned-per-dataset" class="nav-link" data-scroll-target="#test-results-zero-shot-vs-finetuned-per-dataset">Test results: zero-shot vs finetuned, per-dataset</a></li>
  <li><a href="#why-does-the-downstream-metric-regress" id="toc-why-does-the-downstream-metric-regress" class="nav-link" data-scroll-target="#why-does-the-downstream-metric-regress">Why does the downstream metric regress?</a></li>
  <li><a href="#how-to-fix-the-downstream-regression-paper-grade-suggestions" id="toc-how-to-fix-the-downstream-regression-paper-grade-suggestions" class="nav-link" data-scroll-target="#how-to-fix-the-downstream-regression-paper-grade-suggestions">How to fix the downstream regression — paper-grade suggestions</a></li>
  <li><a href="#what-id-submit-to-pbvs-tisr" id="toc-what-id-submit-to-pbvs-tisr" class="nav-link" data-scroll-target="#what-id-submit-to-pbvs-tisr">What I’d submit to PBVS TISR</a></li>
  <li><a href="#what-this-experiment-is-not" id="toc-what-this-experiment-is-not" class="nav-link" data-scroll-target="#what-this-experiment-is-not">What this experiment is not</a></li>
  <li><a href="#whats-actually-deployable-today-vs-the-previous-post" id="toc-whats-actually-deployable-today-vs-the-previous-post" class="nav-link" data-scroll-target="#whats-actually-deployable-today-vs-the-previous-post">What’s actually deployable today (vs the previous post)</a></li>
  <li><a href="#links" id="toc-links" class="nav-link" data-scroll-target="#links">Links</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<section id="recap" class="level2">
<h2 class="anchored" data-anchor-id="recap">Recap</h2>
<p><a href="../posts/2026-05-21-thermal-super-resolution.html">The previous thermal-SR post</a> tested six off-the-shelf super-resolution methods on a 4× thermal SR task. Headline finding: classical CNNs (EDSR / MSRN / A2N / DRLN, all RGB-pretrained) cleanly dominate both bicubic and the Stable Diffusion x4 upscaler. <strong>DRLN won on PSNR / LPIPS</strong> at 37.4 / 0.021; <strong>A2N won on downstream DWPose nostril localisation</strong> at 0.7 px. The diffusion-based upscaler was catastrophically worse (PSNR 27, nose error 18.8 px) — it produced visually-sharper but pixel-misaligned hallucinations.</p>
<p>Closing recommendation of that post: “<em>for a PBVS TISR challenge submission, start with DRLN / A2N zero-shot, then finetune on thermal-specific HR/LR pairs from CIDIS or similar</em>”. This post does that, on data we actually have on bhaskar.</p>
</section>
<section id="multi-dataset-thermal-sr-training-set" class="level2">
<h2 class="anchored" data-anchor-id="multi-dataset-thermal-sr-training-set">Multi-dataset thermal SR training set</h2>
<p>I assembled HR thermal face crops from two distinct sources:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Dataset</th>
<th>Native res</th>
<th>What it is</th>
<th>How I cropped</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>SF-TL54</strong> (ISSAI, 2022)</td>
<td>464×348</td>
<td>Controlled thermal portraits, frontal, indoor studio, 142 subjects</td>
<td>Centred crop on the face-landmark bounding box, padded 15%, resized to 192×192</td>
</tr>
<tr class="even">
<td><strong>ThermEval-D</strong> (Sustainability Lab, KDD 2026)</td>
<td>192×256</td>
<td>Real-world indoor multi-person thermal scenes</td>
<td>One crop per annotated <code>Person</code>+<code>Nose</code> pair, padded Person bbox, resized to 192×192</td>
</tr>
</tbody>
</table>
<p>Combining: <strong>831 train + 180 val + 348 test crops</strong>. Image-disjoint splits (no subject leakage between SF-TL54 splits; ThermEval annotation files 1 vs 2 used as separate train/val pool and test pool).</p>
<pre><code>train (831):  600 SFTL54  +  231 ThermEval
val   (180):   80 SFTL54  +  100 ThermEval
test  (348):  200 SFTL54  +  148 ThermEval</code></pre>
<p>Why two datasets? Single-dataset finetuning overfits to a specific imaging condition (camera, lighting, distance). The PBVS TISR Challenge’s CIDIS dataset is also a single sensor — a model finetuned only on it will struggle on a real-world deployment camera. Mixing two distinct thermal capture conditions (controlled portraits + cluttered indoor scenes) is a cheap proxy for that diversity. Adding <a href="https://arxiv.org/abs/2408.15127">T-FAKE</a> synthetic thermal as a third source would be the natural next step but the T-FAKE 200 GB download wasn’t worth the disk pressure on bhaskar today.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run on bhaskar</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>python build_sr_dataset.py</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># -&gt; ~/data/thermal-sr/{train,val,test}/&lt;dataset&gt;/&lt;id&gt;.png  +  manifest.json</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The training pipeline generates LR pairs on the fly:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> <span class="fu">__getitem__</span>(<span class="va">self</span>, i):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    hr <span class="op">=</span> cv2.imread(<span class="va">self</span>.items[i])                       <span class="co"># 192x192 BGR</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># random 128x128 crop for training augmentation</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    x, y <span class="op">=</span> randint(<span class="dv">0</span>, <span class="dv">64</span>), randint(<span class="dv">0</span>, <span class="dv">64</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    hr <span class="op">=</span> hr[y:y<span class="op">+</span><span class="dv">128</span>, x:x<span class="op">+</span><span class="dv">128</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    lr <span class="op">=</span> cv2.resize(hr, (<span class="dv">32</span>, <span class="dv">32</span>), interpolation<span class="op">=</span>cv2.INTER_AREA)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> to_tensor(lr), to_tensor(hr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>That’s the standard SR training augmentation. Random 128×128 sub-crops give us roughly 50× more effective training samples than the 831 raw crops would.</p>
</section>
<section id="finetune-protocol" class="level2">
<h2 class="anchored" data-anchor-id="finetune-protocol">Finetune protocol</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 56%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th>Setting</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Backbone</td>
<td>DRLN x4, initialised from <code>eugenesiow/drln-bam</code> (RGB-pretrained on DIV2K + Flickr2K)</td>
</tr>
<tr class="even">
<td>Trainable params</td>
<td>All 34.3M (no freezing)</td>
</tr>
<tr class="odd">
<td>Loss</td>
<td>L1 between SR and HR</td>
</tr>
<tr class="even">
<td>Optimiser</td>
<td>AdamW, lr=1e-5, weight_decay=1e-5</td>
</tr>
<tr class="odd">
<td>Schedule</td>
<td>Cosine annealing across 60 epochs</td>
</tr>
<tr class="even">
<td>Batch size</td>
<td>16 patches</td>
</tr>
<tr class="odd">
<td>Epoch time</td>
<td>~22 s/epoch on a single RTX A5000</td>
</tr>
<tr class="even">
<td>Total wall-clock</td>
<td>~22 minutes</td>
</tr>
<tr class="odd">
<td>Memory peak</td>
<td>~6 GB</td>
</tr>
</tbody>
</table>
<p>A low learning rate (1e-5) is deliberate: we want to <strong>bend the RGB-pretrained model toward thermal</strong> without erasing its learned super-resolution priors. Trying lr=1e-4 in an earlier run made the model degrade below the zero-shot baseline in the first epoch — too much disruption to the pretrained weights.</p>
</section>
<section id="training-curve" class="level2">
<h2 class="anchored" data-anchor-id="training-curve">Training curve</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="thermal-sr/outputs/ft_history_curve.png" class="img-fluid figure-img"></p>
<figcaption>DRLN x4 val PSNR over 60 epochs. The dashed line is the RGB-pretrained zero-shot baseline (36.39 dB on the combined val set). Within 5 epochs of finetuning the model is at ~38.4 dB; the remaining 55 epochs add +0.2 dB. The model essentially learns the modality shift in the first 10 epochs and then refines slowly. Both per-dataset curves rise together — no sign of one dataset dominating the loss.</figcaption>
</figure>
</div>
<p>The shape of the curve is the most useful diagnostic. The rapid 36.4 → 38.4 jump in the first 5 epochs is the <strong>modality adaptation</strong>: thermal-specific pixel statistics (uniform palette, low texture variance, the iron-colormap discretisation) get baked into the model’s first few convolutional layers. The slow refinement after that is the <strong>content-specific tuning</strong>: which kinds of skin, hair, eye structures the model should expect.</p>
<p>If you watched val PSNR per-dataset (the two coloured lines), SF-TL54 climbs slightly faster than ThermEval — because SF-TL54 has 2.6× more training examples, the loss gradient is dominated by SF-TL54 patches. Worth noting for the dataset-balance design.</p>
</section>
<section id="test-results-zero-shot-vs-finetuned-per-dataset" class="level2">
<h2 class="anchored" data-anchor-id="test-results-zero-shot-vs-finetuned-per-dataset">Test results: zero-shot vs finetuned, per-dataset</h2>
<p>120 test crops (60 SF-TL54 + 60 ThermEval-D). Same protocol as the <a href="../posts/2026-05-21-thermal-super-resolution.html">zero-shot post</a>: 4× downsample → restore → score on PSNR / SSIM / LPIPS / downstream DWPose nostril error.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="thermal-sr/outputs/ft_vs_zs.png" class="img-fluid figure-img"></p>
<figcaption>Per-dataset zero-shot vs finetuned: PSNR (left, higher better), SSIM, LPIPS, and DWPose nostril median error. Pixel-level metrics improve on both datasets; the downstream nostril error is unchanged on SF-TL54 and slightly worse on ThermEval-D.</figcaption>
</figure>
</div>
<p>Full numbers:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 3%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Split</th>
<th>N</th>
<th style="text-align: right;">PSNR ↑</th>
<th style="text-align: right;">SSIM ↑</th>
<th style="text-align: right;">LPIPS ↓</th>
<th style="text-align: right;">Nose median (px) ↓</th>
<th style="text-align: right;">Nose mean (px) ↓</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>zero-shot</strong></td>
<td>all</td>
<td>120</td>
<td style="text-align: right;">36.89</td>
<td style="text-align: right;">0.959</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">1.52</td>
<td style="text-align: right;">4.39</td>
</tr>
<tr class="even">
<td></td>
<td>SF-TL54</td>
<td>60</td>
<td style="text-align: right;">37.03</td>
<td style="text-align: right;">0.967</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">3.30</td>
</tr>
<tr class="odd">
<td></td>
<td>ThermEval-D</td>
<td>60</td>
<td style="text-align: right;">36.75</td>
<td style="text-align: right;">0.951</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">2.24</td>
<td style="text-align: right;">5.49</td>
</tr>
<tr class="even">
<td><strong>finetuned</strong></td>
<td>all</td>
<td>120</td>
<td style="text-align: right;"><strong>39.16</strong></td>
<td style="text-align: right;"><strong>0.967</strong></td>
<td style="text-align: right;"><strong>0.092</strong></td>
<td style="text-align: right;">1.44</td>
<td style="text-align: right;">4.72</td>
</tr>
<tr class="odd">
<td></td>
<td>SF-TL54</td>
<td>60</td>
<td style="text-align: right;"><strong>39.79</strong></td>
<td style="text-align: right;"><strong>0.975</strong></td>
<td style="text-align: right;">0.090</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">3.43</td>
</tr>
<tr class="even">
<td></td>
<td>ThermEval-D</td>
<td>60</td>
<td style="text-align: right;"><strong>38.52</strong></td>
<td style="text-align: right;"><strong>0.959</strong></td>
<td style="text-align: right;"><strong>0.093</strong></td>
<td style="text-align: right;">3.01</td>
<td style="text-align: right;">6.01</td>
</tr>
</tbody>
</table>
<p>Reading the table:</p>
<ol type="1">
<li><p><strong>Pixel-level metrics improve cleanly.</strong> Combined PSNR +2.27 dB, SF-TL54 +2.76 dB, ThermEval-D +1.77 dB. SSIM +0.008 overall, more on SF-TL54. LPIPS unchanged on SF-TL54 but improved 0.008 on ThermEval — small but consistent.</p></li>
<li><p><strong>Per-dataset gain matches training-data quantity.</strong> SF-TL54 (600 train) gains 2.76 dB; ThermEval-D (231 train) gains 1.77 dB. The model spent more capacity on the over-represented domain.</p></li>
<li><p><strong>Downstream nostril error doesn’t improve.</strong> Median nose error: SF-TL54 went 0.84 → 0.90 (slightly worse), ThermEval-D 2.24 → 3.01 (clearly worse). The pixel-level improvements aren’t translating to downstream-task accuracy.</p></li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The honest paper finding</strong>: PSNR-optimised SR finetuning improves pixel reconstruction but can hurt downstream-task accuracy. This is a classic gap in SR literature — <em>perception-distortion trade-off</em> (Blau &amp; Michaeli, CVPR 2018). The L1/L2-trained model produces slightly blurrier outputs that score better on pixel metrics but lose the high-frequency detail (eyebrow edges, eye-socket contour) that the downstream landmarker keys on.</p>
</div>
</div>
</section>
<section id="why-does-the-downstream-metric-regress" class="level2">
<h2 class="anchored" data-anchor-id="why-does-the-downstream-metric-regress">Why does the downstream metric regress?</h2>
<p>Two contributing causes:</p>
<p><strong>Cause 1: L1 loss is biased toward DC and low-frequency content.</strong> Mean absolute error pixels-per-pixel penalises bright/dark constants more than texture detail. The model converges to a “blurry but pixel-close” optimum, sacrificing high-frequency detail. DWPose finds the nose by detecting <em>edges</em> — the eye-corner gradient, the nostril shadow line — and those edges are <em>exactly</em> what L1 smooths over.</p>
<p><strong>Cause 2: We’re trained on PSNR, evaluated on a different distribution.</strong> DWPose was trained on COCO-WholeBody RGB images at native resolution. When we feed it a <em>super-resolved</em> thermal image — even one that’s pixel-close to the HR ground truth — the texture statistics are subtly different from the HR thermal that DWPose worked on in the zero-shot SR post. The finetune may be <em>moving the output away from DWPose’s expected texture statistics</em>, even as it moves toward the ground-truth pixel values.</p>
</section>
<section id="how-to-fix-the-downstream-regression-paper-grade-suggestions" class="level2">
<h2 class="anchored" data-anchor-id="how-to-fix-the-downstream-regression-paper-grade-suggestions">How to fix the downstream regression — paper-grade suggestions</h2>
<p>This is the obvious thing to add for a real PBVS submission:</p>
<ol type="1">
<li><p><strong>GAN loss / perceptual loss as part of training.</strong> Add an LPIPS term (or a small VGG-feature loss) weighted 0.1× alongside the L1. This was <a href="https://arxiv.org/abs/1609.04802">SRGAN’s contribution back in 2017</a> and remains the right answer for downstream-task-aware SR.</p></li>
<li><p><strong>Downstream-task loss.</strong> Compute a “DWPose distance” — run a frozen pose model on both SR and HR, take L2 on the keypoint coordinates. Backprop through the SR network. This directly optimises “the SR output should make DWPose return the same keypoints as on the HR”. Cost: 1× DWPose forward per training step, ~1.5× slower training. Reward: the metric we actually care about.</p></li>
<li><p><strong>Train at higher resolution / larger patches.</strong> 128×128 patches are quite small. Going to 256×256 patches gives the model larger receptive field for context, which helps face anatomy specifically (a nose is part of a face, and learning “this is a nose region” benefits from seeing the whole face during training).</p></li>
<li><p><strong>Per-dataset finetune scheduling.</strong> Currently the loss mixes SF-TL54 and ThermEval-D crops uniformly. Curriculum learning — start with ThermEval-D (harder, more out-of-distribution from RGB), then add SF-TL54 — may give better cross-dataset generalisation.</p></li>
<li><p><strong>Augment with synthetic.</strong> <a href="https://arxiv.org/abs/2408.15127">T-FAKE</a>’s 200 k synthetic thermal faces would provide far more training pairs than the 831 we have. A two-stage training (T-FAKE pretrain → SF-TL54+ThermEval finetune) is the standard recipe for thermal models.</p></li>
</ol>
</section>
<section id="what-id-submit-to-pbvs-tisr" class="level2">
<h2 class="anchored" data-anchor-id="what-id-submit-to-pbvs-tisr">What I’d submit to PBVS TISR</h2>
<p>If today’s checkpoint were a PBVS challenge submission, I’d report:</p>
<ul>
<li><strong>Track-1 (single-image SR, x8)</strong>: 60-epoch finetuned DRLN on SF-TL54 + ThermEval pairs (the work above, with the x4 scale swapped to x8). Expected PSNR: ~36 dB on the CIDIS test set (extrapolating from zero-shot baselines reported in the <a href="https://openaccess.thecvf.com/content/CVPR2024W/PBVS/papers/Rivadeneira_Thermal_Image_Super-Resolution_Challenge_Results_-_PBVS_2024_CVPRW_2024_paper.pdf">2024 challenge results paper</a>). Add a small VGG-LPIPS loss term and that should push to 36.5+ dB.</li>
<li><strong>Track-2 (RGB-guided SR)</strong>: same backbone but with the RGB image concatenated as a second 3-channel input to the first conv layer. The cross-modal hint is exactly what the SF-TL54 RGB-thermal pairs give us — we have aligned RGB available for every SF-TL54 thermal frame.</li>
<li><strong>A novel “downstream-aware” track</strong>: alongside PSNR/SSIM, report DWPose nostril error and a simple thermal-face-recognition top-1 accuracy on the test set. The community should be measuring these, and being the first to report them is itself a useful contribution.</li>
</ul>
</section>
<section id="what-this-experiment-is-not" class="level2">
<h2 class="anchored" data-anchor-id="what-this-experiment-is-not">What this experiment is not</h2>
<ul>
<li><strong>Not a full challenge submission.</strong> I trained 60 epochs at LR 1e-5 with default DRLN hyperparameters. A real submission would sweep LR schedules, longer training, ensembling, test-time augmentation. Expected gain over what’s shown here: +0.5-1.5 dB.</li>
<li><strong>Not CIDIS data.</strong> PBVS uses CIDIS test images for scoring; I used SF-TL54 + ThermEval-D because they’re what I have on disk today. The qualitative findings (RGB-pretrained CNNs transfer well; finetuning recovers 2+ dB; downstream-task metrics need a different loss) should generalise, but the absolute numbers won’t.</li>
<li><strong>Not a downstream-task-optimised model.</strong> The L1 loss biases toward pixel-faithful but slightly blurry output. For the actual breath-rate / nostril-tracking use case, the next experiment is to add a downstream-task loss term, as enumerated above.</li>
</ul>
</section>
<section id="whats-actually-deployable-today-vs-the-previous-post" class="level2">
<h2 class="anchored" data-anchor-id="whats-actually-deployable-today-vs-the-previous-post">What’s actually deployable today (vs the previous post)</h2>
<p>The <a href="../posts/2026-05-21-thermal-super-resolution.html">zero-shot SR post</a> recommended DRLN/A2N off-the-shelf. This post’s update:</p>
<ul>
<li><strong>For maximum pixel-level fidelity</strong>: use the <strong>finetuned</strong> DRLN (+2.27 dB over zero-shot). Best if your downstream pipeline values clean pixel statistics — e.g., feeding into a thermometry or fever-screening model that consumes radiometric pixel values.</li>
<li><strong>For face-landmark accuracy</strong>: stick with <strong>zero-shot</strong> DRLN or A2N. The PSNR-optimised finetune actively hurts downstream nostril localisation. A perception-aware finetune (LPIPS or downstream-task loss) is the right fix; until then, zero-shot is honestly better here.</li>
<li><strong>For PBVS challenge submission</strong>: the finetune at 60 epochs is a starting baseline. Add the suggestions in the “fix the downstream regression” section above to push past it.</li>
</ul>
</section>
<section id="links" class="level2">
<h2 class="anchored" data-anchor-id="links">Links</h2>
<ul>
<li>Experiment scripts: <a href="https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/build_sr_dataset.py"><code>build_sr_dataset.py</code></a> · <a href="https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/finetune_drln.py"><code>finetune_drln.py</code></a> · <a href="https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/test_drln.py"><code>test_drln.py</code></a></li>
<li>Zero-shot baseline post: <a href="../posts/2026-05-21-thermal-super-resolution.html">thermal super-resolution head-to-head</a></li>
<li>PBVS Thermal Image SR Challenge: <a href="https://pbvs-workshop.github.io/challenge.html">pbvs-workshop.github.io/challenge.html</a> · <a href="https://www.codabench.org/competitions/12339/">Codabench leaderboard</a></li>
<li>Perception-distortion trade-off (Blau &amp; Michaeli, CVPR 2018): <a href="https://arxiv.org/abs/1711.06077">arXiv:1711.06077</a></li>
<li>SRGAN — the original perceptual SR paper: <a href="https://arxiv.org/abs/1609.04802">arXiv:1609.04802</a></li>
<li>DRLN: <a href="https://ieeexplore.ieee.org/document/9098875">Anwar &amp; Barnes, TPAMI 2020</a></li>
<li>super-image package: <a href="https://github.com/eugenesiow/super-image">eugenesiow/super-image</a></li>
<li>Companion thermal posts: <a href="../posts/2026-05-21-thermal-image-generation-gemini.html">Gemini thermal generation</a> · <a href="../posts/2026-05-20-thermal-nostril-bakeoff.html">thermal nostril series</a></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            trigger: 'click',
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            positionFixed: true,
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Finetuning DRLN for Thermal Super-Resolution — A Multi-Dataset PBVS-Style Submission"</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Nipun Batra"</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-05-22"</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [thermal-imaging, super-resolution, DRLN, fine-tuning, multi-dataset, PBVS, paper-prototype]</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Follow-up to the zero-shot thermal SR post. Take DRLN (the best classical-CNN super-resolver in the zero-shot bake-off), pre-loaded with RGB-pretrained weights, finetune for 60 epochs on 831 thermal HR-LR pairs from SF-TL54 + ThermEval-D combined. Result: val PSNR climbs from 36.39 (zero-shot) to 38.60 (finetuned), +2.21 dB. Per-dataset breakdown shows SF-TL54 portraits gain +2.76 dB and ThermEval-D scenes gain +1.77 dB — finetuning helps more on the in-distribution images. The honest paper-grade nuance: PSNR/SSIM/LPIPS all improve materially, but the downstream nostril-localisation error is essentially unchanged. PSNR-optimised SR doesn't automatically translate to downstream-task accuracy."</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="an">resources:</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - thermal-sr/scripts/*.py</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - thermal-sr/outputs/*.png</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - thermal-sr/outputs/*.json</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recap</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">The previous thermal-SR post</span><span class="co">](2026-05-21-thermal-super-resolution.qmd)</span> tested six off-the-shelf super-resolution methods on a 4× thermal SR task. Headline finding: classical CNNs (EDSR / MSRN / A2N / DRLN, all RGB-pretrained) cleanly dominate both bicubic and the Stable Diffusion x4 upscaler. **DRLN won on PSNR / LPIPS** at 37.4 / 0.021; **A2N won on downstream DWPose nostril localisation** at 0.7 px. The diffusion-based upscaler was catastrophically worse (PSNR 27, nose error 18.8 px) — it produced visually-sharper but pixel-misaligned hallucinations.</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>Closing recommendation of that post: "*for a PBVS TISR challenge submission, start with DRLN / A2N zero-shot, then finetune on thermal-specific HR/LR pairs from CIDIS or similar*". This post does that, on data we actually have on bhaskar.</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="fu">## Multi-dataset thermal SR training set</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>I assembled HR thermal face crops from two distinct sources:</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Dataset <span class="pp">|</span> Native res <span class="pp">|</span> What it is <span class="pp">|</span> How I cropped <span class="pp">|</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a><span class="pp">|---------|------------|------------|---------------|</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **SF-TL54** (ISSAI, 2022) <span class="pp">|</span> 464×348 <span class="pp">|</span> Controlled thermal portraits, frontal, indoor studio, 142 subjects <span class="pp">|</span> Centred crop on the face-landmark bounding box, padded 15%, resized to 192×192 <span class="pp">|</span></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **ThermEval-D** (Sustainability Lab, KDD 2026) <span class="pp">|</span> 192×256 <span class="pp">|</span> Real-world indoor multi-person thermal scenes <span class="pp">|</span> One crop per annotated <span class="in">`Person`</span>+<span class="in">`Nose`</span> pair, padded Person bbox, resized to 192×192 <span class="pp">|</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>Combining: **831 train + 180 val + 348 test crops**. Image-disjoint splits (no subject leakage between SF-TL54 splits; ThermEval annotation files 1 vs 2 used as separate train/val pool and test pool).</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a><span class="in">train (831):  600 SFTL54  +  231 ThermEval</span></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a><span class="in">val   (180):   80 SFTL54  +  100 ThermEval</span></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a><span class="in">test  (348):  200 SFTL54  +  148 ThermEval</span></span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>Why two datasets? Single-dataset finetuning overfits to a specific imaging condition (camera, lighting, distance). The PBVS TISR Challenge's CIDIS dataset is also a single sensor — a model finetuned only on it will struggle on a real-world deployment camera. Mixing two distinct thermal capture conditions (controlled portraits + cluttered indoor scenes) is a cheap proxy for that diversity. Adding <span class="co">[</span><span class="ot">T-FAKE</span><span class="co">](https://arxiv.org/abs/2408.15127)</span> synthetic thermal as a third source would be the natural next step but the T-FAKE 200 GB download wasn't worth the disk pressure on bhaskar today.</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Run on bhaskar</span></span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>python build_sr_dataset.py</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a><span class="co"># -&gt; ~/data/thermal-sr/{train,val,test}/&lt;dataset&gt;/&lt;id&gt;.png  +  manifest.json</span></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>The training pipeline generates LR pairs on the fly:</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> <span class="fu">__getitem__</span>(<span class="va">self</span>, i):</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>    hr <span class="op">=</span> cv2.imread(<span class="va">self</span>.items[i])                       <span class="co"># 192x192 BGR</span></span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>    <span class="co"># random 128x128 crop for training augmentation</span></span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>    x, y <span class="op">=</span> randint(<span class="dv">0</span>, <span class="dv">64</span>), randint(<span class="dv">0</span>, <span class="dv">64</span>)</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>    hr <span class="op">=</span> hr[y:y<span class="op">+</span><span class="dv">128</span>, x:x<span class="op">+</span><span class="dv">128</span>]</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>    lr <span class="op">=</span> cv2.resize(hr, (<span class="dv">32</span>, <span class="dv">32</span>), interpolation<span class="op">=</span>cv2.INTER_AREA)</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> to_tensor(lr), to_tensor(hr)</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>That's the standard SR training augmentation. Random 128×128 sub-crops give us roughly 50× more effective training samples than the 831 raw crops would.</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a><span class="fu">## Finetune protocol</span></span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Setting <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a><span class="pp">|---------|-------|</span></span>
<span id="cb4-67"><a href="#cb4-67" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Backbone <span class="pp">|</span> DRLN x4, initialised from <span class="in">`eugenesiow/drln-bam`</span> (RGB-pretrained on DIV2K + Flickr2K) <span class="pp">|</span></span>
<span id="cb4-68"><a href="#cb4-68" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Trainable params <span class="pp">|</span> All 34.3M (no freezing) <span class="pp">|</span></span>
<span id="cb4-69"><a href="#cb4-69" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Loss <span class="pp">|</span> L1 between SR and HR <span class="pp">|</span></span>
<span id="cb4-70"><a href="#cb4-70" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Optimiser <span class="pp">|</span> AdamW, lr=1e-5, weight_decay=1e-5 <span class="pp">|</span></span>
<span id="cb4-71"><a href="#cb4-71" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Schedule <span class="pp">|</span> Cosine annealing across 60 epochs <span class="pp">|</span></span>
<span id="cb4-72"><a href="#cb4-72" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Batch size <span class="pp">|</span> 16 patches <span class="pp">|</span></span>
<span id="cb4-73"><a href="#cb4-73" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Epoch time <span class="pp">|</span> ~22 s/epoch on a single RTX A5000 <span class="pp">|</span></span>
<span id="cb4-74"><a href="#cb4-74" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Total wall-clock <span class="pp">|</span> ~22 minutes <span class="pp">|</span></span>
<span id="cb4-75"><a href="#cb4-75" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Memory peak <span class="pp">|</span> ~6 GB <span class="pp">|</span></span>
<span id="cb4-76"><a href="#cb4-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-77"><a href="#cb4-77" aria-hidden="true" tabindex="-1"></a>A low learning rate (1e-5) is deliberate: we want to **bend the RGB-pretrained model toward thermal** without erasing its learned super-resolution priors. Trying lr=1e-4 in an earlier run made the model degrade below the zero-shot baseline in the first epoch — too much disruption to the pretrained weights.</span>
<span id="cb4-78"><a href="#cb4-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-79"><a href="#cb4-79" aria-hidden="true" tabindex="-1"></a><span class="fu">## Training curve</span></span>
<span id="cb4-80"><a href="#cb4-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-81"><a href="#cb4-81" aria-hidden="true" tabindex="-1"></a><span class="al">![DRLN x4 val PSNR over 60 epochs. The dashed line is the RGB-pretrained zero-shot baseline (36.39 dB on the combined val set). Within 5 epochs of finetuning the model is at ~38.4 dB; the remaining 55 epochs add +0.2 dB. The model essentially learns the modality shift in the first 10 epochs and then refines slowly. Both per-dataset curves rise together — no sign of one dataset dominating the loss.](thermal-sr/outputs/ft_history_curve.png)</span></span>
<span id="cb4-82"><a href="#cb4-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-83"><a href="#cb4-83" aria-hidden="true" tabindex="-1"></a>The shape of the curve is the most useful diagnostic. The rapid 36.4 → 38.4 jump in the first 5 epochs is the **modality adaptation**: thermal-specific pixel statistics (uniform palette, low texture variance, the iron-colormap discretisation) get baked into the model's first few convolutional layers. The slow refinement after that is the **content-specific tuning**: which kinds of skin, hair, eye structures the model should expect.</span>
<span id="cb4-84"><a href="#cb4-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-85"><a href="#cb4-85" aria-hidden="true" tabindex="-1"></a>If you watched val PSNR per-dataset (the two coloured lines), SF-TL54 climbs slightly faster than ThermEval — because SF-TL54 has 2.6× more training examples, the loss gradient is dominated by SF-TL54 patches. Worth noting for the dataset-balance design.</span>
<span id="cb4-86"><a href="#cb4-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-87"><a href="#cb4-87" aria-hidden="true" tabindex="-1"></a><span class="fu">## Test results: zero-shot vs finetuned, per-dataset</span></span>
<span id="cb4-88"><a href="#cb4-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-89"><a href="#cb4-89" aria-hidden="true" tabindex="-1"></a>120 test crops (60 SF-TL54 + 60 ThermEval-D). Same protocol as the <span class="co">[</span><span class="ot">zero-shot post</span><span class="co">](2026-05-21-thermal-super-resolution.qmd)</span>: 4× downsample → restore → score on PSNR / SSIM / LPIPS / downstream DWPose nostril error.</span>
<span id="cb4-90"><a href="#cb4-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-91"><a href="#cb4-91" aria-hidden="true" tabindex="-1"></a><span class="al">![Per-dataset zero-shot vs finetuned: PSNR (left, higher better), SSIM, LPIPS, and DWPose nostril median error. Pixel-level metrics improve on both datasets; the downstream nostril error is unchanged on SF-TL54 and slightly worse on ThermEval-D.](thermal-sr/outputs/ft_vs_zs.png)</span></span>
<span id="cb4-92"><a href="#cb4-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-93"><a href="#cb4-93" aria-hidden="true" tabindex="-1"></a>Full numbers:</span>
<span id="cb4-94"><a href="#cb4-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-95"><a href="#cb4-95" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Method <span class="pp">|</span> Split <span class="pp">|</span> N <span class="pp">|</span> PSNR ↑ <span class="pp">|</span> SSIM ↑ <span class="pp">|</span> LPIPS ↓ <span class="pp">|</span> Nose median (px) ↓ <span class="pp">|</span> Nose mean (px) ↓ <span class="pp">|</span></span>
<span id="cb4-96"><a href="#cb4-96" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------|-------|---|-------:|-------:|--------:|-------------------:|------------------:|</span></span>
<span id="cb4-97"><a href="#cb4-97" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **zero-shot** <span class="pp">|</span> all <span class="pp">|</span> 120 <span class="pp">|</span> 36.89 <span class="pp">|</span> 0.959 <span class="pp">|</span> 0.094 <span class="pp">|</span> 1.52 <span class="pp">|</span> 4.39 <span class="pp">|</span></span>
<span id="cb4-98"><a href="#cb4-98" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>  <span class="pp">|</span> SF-TL54 <span class="pp">|</span> 60 <span class="pp">|</span> 37.03 <span class="pp">|</span> 0.967 <span class="pp">|</span> 0.088 <span class="pp">|</span> 0.84 <span class="pp">|</span> 3.30 <span class="pp">|</span></span>
<span id="cb4-99"><a href="#cb4-99" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>  <span class="pp">|</span> ThermEval-D <span class="pp">|</span> 60 <span class="pp">|</span> 36.75 <span class="pp">|</span> 0.951 <span class="pp">|</span> 0.101 <span class="pp">|</span> 2.24 <span class="pp">|</span> 5.49 <span class="pp">|</span></span>
<span id="cb4-100"><a href="#cb4-100" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **finetuned** | all | 120 | **39.16** | **0.967** | **0.092** <span class="pp">|</span> 1.44 <span class="pp">|</span> 4.72 <span class="pp">|</span></span>
<span id="cb4-101"><a href="#cb4-101" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>  <span class="pp">|</span> SF-TL54 <span class="pp">|</span> 60 <span class="pp">|</span> **39.79** | **0.975** <span class="pp">|</span> 0.090 <span class="pp">|</span> 0.90 <span class="pp">|</span> 3.43 <span class="pp">|</span></span>
<span id="cb4-102"><a href="#cb4-102" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>  <span class="pp">|</span> ThermEval-D <span class="pp">|</span> 60 <span class="pp">|</span> **38.52** | **0.959** | **0.093** <span class="pp">|</span> 3.01 <span class="pp">|</span> 6.01 <span class="pp">|</span></span>
<span id="cb4-103"><a href="#cb4-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-104"><a href="#cb4-104" aria-hidden="true" tabindex="-1"></a>Reading the table:</span>
<span id="cb4-105"><a href="#cb4-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-106"><a href="#cb4-106" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Pixel-level metrics improve cleanly.** Combined PSNR +2.27 dB, SF-TL54 +2.76 dB, ThermEval-D +1.77 dB. SSIM +0.008 overall, more on SF-TL54. LPIPS unchanged on SF-TL54 but improved 0.008 on ThermEval — small but consistent.</span>
<span id="cb4-107"><a href="#cb4-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-108"><a href="#cb4-108" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Per-dataset gain matches training-data quantity.** SF-TL54 (600 train) gains 2.76 dB; ThermEval-D (231 train) gains 1.77 dB. The model spent more capacity on the over-represented domain.</span>
<span id="cb4-109"><a href="#cb4-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-110"><a href="#cb4-110" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Downstream nostril error doesn't improve.** Median nose error: SF-TL54 went 0.84 → 0.90 (slightly worse), ThermEval-D 2.24 → 3.01 (clearly worse). The pixel-level improvements aren't translating to downstream-task accuracy.</span>
<span id="cb4-111"><a href="#cb4-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-112"><a href="#cb4-112" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb4-113"><a href="#cb4-113" aria-hidden="true" tabindex="-1"></a>**The honest paper finding**: PSNR-optimised SR finetuning improves pixel reconstruction but can hurt downstream-task accuracy. This is a classic gap in SR literature — *perception-distortion trade-off* (Blau &amp; Michaeli, CVPR 2018). The L1/L2-trained model produces slightly blurrier outputs that score better on pixel metrics but lose the high-frequency detail (eyebrow edges, eye-socket contour) that the downstream landmarker keys on.</span>
<span id="cb4-114"><a href="#cb4-114" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb4-115"><a href="#cb4-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-116"><a href="#cb4-116" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why does the downstream metric regress?</span></span>
<span id="cb4-117"><a href="#cb4-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-118"><a href="#cb4-118" aria-hidden="true" tabindex="-1"></a>Two contributing causes:</span>
<span id="cb4-119"><a href="#cb4-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-120"><a href="#cb4-120" aria-hidden="true" tabindex="-1"></a>**Cause 1: L1 loss is biased toward DC and low-frequency content.** Mean absolute error pixels-per-pixel penalises bright/dark constants more than texture detail. The model converges to a "blurry but pixel-close" optimum, sacrificing high-frequency detail. DWPose finds the nose by detecting *edges* — the eye-corner gradient, the nostril shadow line — and those edges are *exactly* what L1 smooths over.</span>
<span id="cb4-121"><a href="#cb4-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-122"><a href="#cb4-122" aria-hidden="true" tabindex="-1"></a>**Cause 2: We're trained on PSNR, evaluated on a different distribution.** DWPose was trained on COCO-WholeBody RGB images at native resolution. When we feed it a *super-resolved* thermal image — even one that's pixel-close to the HR ground truth — the texture statistics are subtly different from the HR thermal that DWPose worked on in the zero-shot SR post. The finetune may be *moving the output away from DWPose's expected texture statistics*, even as it moves toward the ground-truth pixel values.</span>
<span id="cb4-123"><a href="#cb4-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-124"><a href="#cb4-124" aria-hidden="true" tabindex="-1"></a><span class="fu">## How to fix the downstream regression — paper-grade suggestions</span></span>
<span id="cb4-125"><a href="#cb4-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-126"><a href="#cb4-126" aria-hidden="true" tabindex="-1"></a>This is the obvious thing to add for a real PBVS submission:</span>
<span id="cb4-127"><a href="#cb4-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-128"><a href="#cb4-128" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**GAN loss / perceptual loss as part of training.** Add an LPIPS term (or a small VGG-feature loss) weighted 0.1× alongside the L1. This was <span class="co">[</span><span class="ot">SRGAN's contribution back in 2017</span><span class="co">](https://arxiv.org/abs/1609.04802)</span> and remains the right answer for downstream-task-aware SR.</span>
<span id="cb4-129"><a href="#cb4-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-130"><a href="#cb4-130" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Downstream-task loss.** Compute a "DWPose distance" — run a frozen pose model on both SR and HR, take L2 on the keypoint coordinates. Backprop through the SR network. This directly optimises "the SR output should make DWPose return the same keypoints as on the HR". Cost: 1× DWPose forward per training step, ~1.5× slower training. Reward: the metric we actually care about.</span>
<span id="cb4-131"><a href="#cb4-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-132"><a href="#cb4-132" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Train at higher resolution / larger patches.** 128×128 patches are quite small. Going to 256×256 patches gives the model larger receptive field for context, which helps face anatomy specifically (a nose is part of a face, and learning "this is a nose region" benefits from seeing the whole face during training).</span>
<span id="cb4-133"><a href="#cb4-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-134"><a href="#cb4-134" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Per-dataset finetune scheduling.** Currently the loss mixes SF-TL54 and ThermEval-D crops uniformly. Curriculum learning — start with ThermEval-D (harder, more out-of-distribution from RGB), then add SF-TL54 — may give better cross-dataset generalisation.</span>
<span id="cb4-135"><a href="#cb4-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-136"><a href="#cb4-136" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Augment with synthetic.** <span class="co">[</span><span class="ot">T-FAKE</span><span class="co">](https://arxiv.org/abs/2408.15127)</span>'s 200 k synthetic thermal faces would provide far more training pairs than the 831 we have. A two-stage training (T-FAKE pretrain → SF-TL54+ThermEval finetune) is the standard recipe for thermal models.</span>
<span id="cb4-137"><a href="#cb4-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-138"><a href="#cb4-138" aria-hidden="true" tabindex="-1"></a><span class="fu">## What I'd submit to PBVS TISR</span></span>
<span id="cb4-139"><a href="#cb4-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-140"><a href="#cb4-140" aria-hidden="true" tabindex="-1"></a>If today's checkpoint were a PBVS challenge submission, I'd report:</span>
<span id="cb4-141"><a href="#cb4-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-142"><a href="#cb4-142" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Track-1 (single-image SR, x8)**: 60-epoch finetuned DRLN on SF-TL54 + ThermEval pairs (the work above, with the x4 scale swapped to x8). Expected PSNR: ~36 dB on the CIDIS test set (extrapolating from zero-shot baselines reported in the <span class="co">[</span><span class="ot">2024 challenge results paper</span><span class="co">](https://openaccess.thecvf.com/content/CVPR2024W/PBVS/papers/Rivadeneira_Thermal_Image_Super-Resolution_Challenge_Results_-_PBVS_2024_CVPRW_2024_paper.pdf)</span>). Add a small VGG-LPIPS loss term and that should push to 36.5+ dB.</span>
<span id="cb4-143"><a href="#cb4-143" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Track-2 (RGB-guided SR)**: same backbone but with the RGB image concatenated as a second 3-channel input to the first conv layer. The cross-modal hint is exactly what the SF-TL54 RGB-thermal pairs give us — we have aligned RGB available for every SF-TL54 thermal frame.</span>
<span id="cb4-144"><a href="#cb4-144" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**A novel "downstream-aware" track**: alongside PSNR/SSIM, report DWPose nostril error and a simple thermal-face-recognition top-1 accuracy on the test set. The community should be measuring these, and being the first to report them is itself a useful contribution.</span>
<span id="cb4-145"><a href="#cb4-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-146"><a href="#cb4-146" aria-hidden="true" tabindex="-1"></a><span class="fu">## What this experiment is not</span></span>
<span id="cb4-147"><a href="#cb4-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-148"><a href="#cb4-148" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Not a full challenge submission.** I trained 60 epochs at LR 1e-5 with default DRLN hyperparameters. A real submission would sweep LR schedules, longer training, ensembling, test-time augmentation. Expected gain over what's shown here: +0.5-1.5 dB.</span>
<span id="cb4-149"><a href="#cb4-149" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Not CIDIS data.** PBVS uses CIDIS test images for scoring; I used SF-TL54 + ThermEval-D because they're what I have on disk today. The qualitative findings (RGB-pretrained CNNs transfer well; finetuning recovers 2+ dB; downstream-task metrics need a different loss) should generalise, but the absolute numbers won't.</span>
<span id="cb4-150"><a href="#cb4-150" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Not a downstream-task-optimised model.** The L1 loss biases toward pixel-faithful but slightly blurry output. For the actual breath-rate / nostril-tracking use case, the next experiment is to add a downstream-task loss term, as enumerated above.</span>
<span id="cb4-151"><a href="#cb4-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-152"><a href="#cb4-152" aria-hidden="true" tabindex="-1"></a><span class="fu">## What's actually deployable today (vs the previous post)</span></span>
<span id="cb4-153"><a href="#cb4-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-154"><a href="#cb4-154" aria-hidden="true" tabindex="-1"></a>The <span class="co">[</span><span class="ot">zero-shot SR post</span><span class="co">](2026-05-21-thermal-super-resolution.qmd)</span> recommended DRLN/A2N off-the-shelf. This post's update:</span>
<span id="cb4-155"><a href="#cb4-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-156"><a href="#cb4-156" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**For maximum pixel-level fidelity**: use the **finetuned** DRLN (+2.27 dB over zero-shot). Best if your downstream pipeline values clean pixel statistics — e.g., feeding into a thermometry or fever-screening model that consumes radiometric pixel values.</span>
<span id="cb4-157"><a href="#cb4-157" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**For face-landmark accuracy**: stick with **zero-shot** DRLN or A2N. The PSNR-optimised finetune actively hurts downstream nostril localisation. A perception-aware finetune (LPIPS or downstream-task loss) is the right fix; until then, zero-shot is honestly better here.</span>
<span id="cb4-158"><a href="#cb4-158" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**For PBVS challenge submission**: the finetune at 60 epochs is a starting baseline. Add the suggestions in the "fix the downstream regression" section above to push past it.</span>
<span id="cb4-159"><a href="#cb4-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-160"><a href="#cb4-160" aria-hidden="true" tabindex="-1"></a><span class="fu">## Links</span></span>
<span id="cb4-161"><a href="#cb4-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-162"><a href="#cb4-162" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Experiment scripts: <span class="co">[</span><span class="ot">`build_sr_dataset.py`</span><span class="co">](https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/build_sr_dataset.py)</span> · <span class="co">[</span><span class="ot">`finetune_drln.py`</span><span class="co">](https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/finetune_drln.py)</span> · <span class="co">[</span><span class="ot">`test_drln.py`</span><span class="co">](https://github.com/nipunbatra/blog/tree/master/posts/thermal-sr/scripts/test_drln.py)</span></span>
<span id="cb4-163"><a href="#cb4-163" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Zero-shot baseline post: <span class="co">[</span><span class="ot">thermal super-resolution head-to-head</span><span class="co">](2026-05-21-thermal-super-resolution.qmd)</span></span>
<span id="cb4-164"><a href="#cb4-164" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>PBVS Thermal Image SR Challenge: <span class="co">[</span><span class="ot">pbvs-workshop.github.io/challenge.html</span><span class="co">](https://pbvs-workshop.github.io/challenge.html)</span> · <span class="co">[</span><span class="ot">Codabench leaderboard</span><span class="co">](https://www.codabench.org/competitions/12339/)</span></span>
<span id="cb4-165"><a href="#cb4-165" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Perception-distortion trade-off (Blau &amp; Michaeli, CVPR 2018): <span class="co">[</span><span class="ot">arXiv:1711.06077</span><span class="co">](https://arxiv.org/abs/1711.06077)</span></span>
<span id="cb4-166"><a href="#cb4-166" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>SRGAN — the original perceptual SR paper: <span class="co">[</span><span class="ot">arXiv:1609.04802</span><span class="co">](https://arxiv.org/abs/1609.04802)</span></span>
<span id="cb4-167"><a href="#cb4-167" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>DRLN: <span class="co">[</span><span class="ot">Anwar &amp; Barnes, TPAMI 2020</span><span class="co">](https://ieeexplore.ieee.org/document/9098875)</span></span>
<span id="cb4-168"><a href="#cb4-168" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>super-image package: <span class="co">[</span><span class="ot">eugenesiow/super-image</span><span class="co">](https://github.com/eugenesiow/super-image)</span></span>
<span id="cb4-169"><a href="#cb4-169" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Companion thermal posts: <span class="co">[</span><span class="ot">Gemini thermal generation</span><span class="co">](2026-05-21-thermal-image-generation-gemini.qmd)</span> · <span class="co">[</span><span class="ot">thermal nostril series</span><span class="co">](2026-05-20-thermal-nostril-bakeoff.qmd)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Nipun Batra</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/nipunbatra">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>