<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nipun Batra">
<meta name="dcterms.date" content="2026-05-20">
<meta name="description" content="Off-the-shelf wholebody pose / face mesh models on the ThermEval-D real-world thermal dataset (192x256, indoor multi-person scenes). On the smallest-face thermal regime that actually matches real deployment, DWPose wins decisively: 100% detection rate, 99% PCK@10px. Sapiens2-0.4b is accurate (2 px median on the noses it finds) but its single-person inference misses 32% of multi-person scenes. MediaPipe FaceMesh detects only 14% of GT noses because the 20-25 px faces in ThermEval are below BlazeFace short-range’s working scale. The pipeline lesson is that for thermal deployment you need a model that includes its own multi-person face detector — not just a strong landmark head.">

<title>A Bake-off for Nostril Detection on Real-World Thermal Scenes (ThermEval-D) – Nipun Batra Blog</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-577833abe1b92350236646abf7bf8d21.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-82e37cb7b6434006901e7fa82e7d06ec.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-577833abe1b92350236646abf7bf8d21.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9482772de5f96bc669c49da57733e8fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-ba0ea52c466f323bb4a80d9892c7c8cb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-9482772de5f96bc669c49da57733e8fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta property="og:title" content="A Bake-off for Nostril Detection on Real-World Thermal Scenes (ThermEval-D) – Nipun Batra Blog">
<meta property="og:description" content="Off-the-shelf wholebody pose / face mesh models on the ThermEval-D real-world thermal dataset (192x256, indoor multi-person scenes). On the smallest-face thermal regime that actually matches real deployment, DWPose wins decisively: 100% detection rate, 99% PCK@10px. Sapiens2-0.4b is accurate (2 px median on the noses it finds) but its single-person inference misses 32% of multi-person scenes. MediaPipe FaceMesh detects only 14% of GT noses because the 20-25 px faces in ThermEval are below BlazeFace short-range’s working scale. The pipeline lesson is that for thermal deployment you need a model that includes its own multi-person face detector — not just a strong landmark head.">
<meta property="og:image" content="nostril-bench/inputs/sample_thermeval.png">
<meta property="og:site_name" content="Nipun Batra Blog">
<meta name="twitter:title" content="A Bake-off for Nostril Detection on Real-World Thermal Scenes (ThermEval-D) – Nipun Batra Blog">
<meta name="twitter:description" content="Off-the-shelf wholebody pose / face mesh models on the ThermEval-D real-world thermal dataset (192x256, indoor multi-person scenes). On the smallest-face thermal regime that actually matches real deployment, DWPose wins decisively: 100% detection rate, 99% PCK@10px. Sapiens2-0.4b is accurate (2 px median on the noses it finds) but its single-person inference misses 32% of multi-person scenes. MediaPipe FaceMesh detects only 14% of GT noses because the 20-25 px faces in ThermEval are below BlazeFace short-range’s working scale. The pipeline lesson is that for thermal deployment you need a model that includes its own multi-person face detector — not just a strong landmark head.">
<meta name="twitter:image" content="nostril-bench/inputs/sample_thermeval.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Nipun Batra Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://nipunbatra.github.io"> 
<span class="menu-text">Homepage</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">A Bake-off for Nostril Detection on Real-World Thermal Scenes (ThermEval-D)</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                  <div>
        <div class="description">
          Off-the-shelf wholebody pose / face mesh models on the ThermEval-D real-world thermal dataset (192x256, indoor multi-person scenes). On the smallest-face thermal regime that actually matches real deployment, DWPose wins decisively: 100% detection rate, 99% PCK@10px. Sapiens2-0.4b is accurate (2 px median on the noses it finds) but its single-person inference misses 32% of multi-person scenes. MediaPipe FaceMesh detects only 14% of GT noses because the 20-25 px faces in ThermEval are below BlazeFace short-range’s working scale. The pipeline lesson is that for thermal deployment you need a model that includes its own multi-person face detector — not just a strong landmark head.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">thermal-imaging</div>
                <div class="quarto-category">keypoint-detection</div>
                <div class="quarto-category">Sapiens2</div>
                <div class="quarto-category">DWPose</div>
                <div class="quarto-category">MediaPipe</div>
                <div class="quarto-category">ViTPose</div>
                <div class="quarto-category">pose-estimation</div>
                <div class="quarto-category">benchmark</div>
                <div class="quarto-category">breath-monitoring</div>
                <div class="quarto-category">ThermEval</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Nipun Batra </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 20, 2026</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">May 21, 2026</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#thermeval-d-whats-in-it" id="toc-thermeval-d-whats-in-it" class="nav-link active" data-scroll-target="#thermeval-d-whats-in-it">ThermEval-D — what’s in it</a></li>
  <li><a href="#the-four-contenders" id="toc-the-four-contenders" class="nav-link" data-scroll-target="#the-four-contenders">The four contenders</a></li>
  <li><a href="#matching-predictions-to-ground-truth" id="toc-matching-predictions-to-ground-truth" class="nav-link" data-scroll-target="#matching-predictions-to-ground-truth">Matching predictions to ground-truth</a></li>
  <li><a href="#headline-result" id="toc-headline-result" class="nav-link" data-scroll-target="#headline-result">Headline result</a></li>
  <li><a href="#what-it-looks-like-six-representative-frames" id="toc-what-it-looks-like-six-representative-frames" class="nav-link" data-scroll-target="#what-it-looks-like-six-representative-frames">What it looks like — six representative frames</a></li>
  <li><a href="#speed" id="toc-speed" class="nav-link" data-scroll-target="#speed">Speed</a></li>
  <li><a href="#why-mediapipes-number-looks-so-much-worse-than-on-the-sf-tl54-v2-of-this-post" id="toc-why-mediapipes-number-looks-so-much-worse-than-on-the-sf-tl54-v2-of-this-post" class="nav-link" data-scroll-target="#why-mediapipes-number-looks-so-much-worse-than-on-the-sf-tl54-v2-of-this-post">Why MediaPipe’s number looks so much worse than on the SF-TL54 v2 of this post</a></li>
  <li><a href="#takeaways" id="toc-takeaways" class="nav-link" data-scroll-target="#takeaways">Takeaways</a></li>
  <li><a href="#limitations-worth-being-explicit-about" id="toc-limitations-worth-being-explicit-about" class="nav-link" data-scroll-target="#limitations-worth-being-explicit-about">Limitations worth being explicit about</a></li>
  <li><a href="#links" id="toc-links" class="nav-link" data-scroll-target="#links">Links</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Update history:</strong> - <strong>2026-05-20 (morning)</strong> v1: Bake-off on SF-TL54 portraits with a hard-coded keypoint-index bug that made Sapiens2 look like it failed catastrophically. - <strong>2026-05-20 (afternoon)</strong> v2: Fixed the index bug by looking up landmarks <strong>by name</strong> from <code>pose_metainfo</code>. Both Sapiens2 and DWPose hit ~4 px on SF-TL54. - <strong>2026-05-21</strong> (this version): Switched the dataset to <a href="https://www.kaggle.com/datasets/shriayush/thermeval"><strong>ThermEval-D</strong></a> (KDD 2026), which is much closer to real deployment — small faces, multi-person, indoor environments at 192×256 — rather than SF-TL54’s controlled close-up portraits. The headline result changes meaningfully: at deployment-realistic face scales, <strong>DWPose wins decisively over Sapiens2 and MediaPipe</strong>, and the differentiator is <em>detection rate</em> (does the model even find the face), not pixel-level accuracy.</p>
</div>
</div>
<p>I want to detect <strong>nostrils in thermal images</strong> for breath-rate monitoring. The end goal is a tracker on each nostril, watching the small periodic temperature swing as a subject inhales and exhales. The pipeline starts with one question: <strong>can an off-the-shelf face / pose / wholebody-keypoint model just <em>find</em> the nostrils on a thermal face in a real scene?</strong></p>
<p>This post answers that for four widely used models, on the <a href="https://www.kaggle.com/datasets/shriayush/thermeval">ThermEval-D dataset</a> — a 1,049-frame thermal benchmark from the <a href="https://sustainability-lab.github.io/">Sustainability Lab at IIT Gandhinagar</a> (KDD 2026), with per-pixel temperature, polygon-segmented <code>Person</code> / <code>Chest</code> / <code>Forehead</code> / <code>Nose</code> annotations, and an honest distribution of small faces in cluttered indoor scenes.</p>
<p>This is part 1 of a four-post series:</p>
<ol type="1">
<li><strong>(this post)</strong> Off-the-shelf bake-off — which existing model gets you closest to the nostrils on thermal, for free?</li>
<li><a href="../posts/2026-05-20-thermal-nostril-finetune.html">Finetuning Sapiens2 on 1-2 keypoints with a tiny labeled set</a>.</li>
<li><a href="../posts/2026-05-20-thermal-nostril-hierarchical.html">Hierarchical face → nostril detector</a> — why two stages beat one for tiny landmarks.</li>
<li><a href="../posts/2026-05-20-thermal-nostril-why-hard.html">Why nostril detection on thermal is fundamentally harder than on RGB</a>.</li>
</ol>
<blockquote class="blockquote">
<p>Code: <a href="https://github.com/nipunbatra/blog/tree/master/posts/nostril-bench/scripts"><code>posts/nostril-bench/scripts/</code></a> — <code>run_all.py</code>, <code>run_thermeval.py</code>, <code>make_thermeval_charts.py</code>.</p>
</blockquote>
<section id="thermeval-d-whats-in-it" class="level2">
<h2 class="anchored" data-anchor-id="thermeval-d-whats-in-it">ThermEval-D — what’s in it</h2>
<p><a href="https://www.kaggle.com/datasets/shriayush/thermeval">ThermEval-D</a> is one of two components of the <a href="https://sustainability-lab.github.io/thermeval/">ThermEval benchmark</a> (Sustainability Lab @ IIT Gandhinagar, KDD 2026). 1,049 thermal frames captured with a TOPDON TC001+ camera (sub-40 mK sensitivity, ±1°C accuracy), each:</p>
<ul>
<li><strong>Image format</strong>: 192×256 8-bit thermal PNG (visualisation) + a paired 16-bit <code>.tiff</code> per-pixel radiometric temperature matrix.</li>
<li><strong>Annotations</strong>: COCO format with four classes — <code>Person</code>, <code>Chest</code>, <code>Forehead</code>, <code>Nose</code> — each as polygon segmentations + bbox. Two annotation files (split 1: 510 frames, split 2: 538 frames).</li>
<li><strong>Distribution</strong>: 256 of 510 frames in split 1 have all four classes; 83 frames have multiple <code>Person</code> instances; ~287/510 have at least one <code>Nose</code> annotation.</li>
</ul>
<p>What “real-world” looks like in this dataset:</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-sample-thermeval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sample-thermeval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="nostril-bench/inputs/sample_thermeval.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sample-thermeval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Two people at desks. The nose region is 5×7 px; the whole face is ~20×25 px in a 192×256 frame.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-sample-thermeval-annot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sample-thermeval-annot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="nostril-bench/inputs/sample_thermeval_annot.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sample-thermeval-annot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Same frame with ground-truth annotations overlaid: Person bbox (blue), Forehead (yellow), Nose (green), nose centroid (red cross). Both faces have full annotations.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Compared to a controlled portrait dataset like SF-TL54 (where the face fills 40% of the frame), the ThermEval-D faces are roughly <strong>30× smaller in pixel area</strong>. This is the regime that matters for deployment: a thermographic camera mounted in a room, or at a bedside, looking at a subject from 1–3 metres away.</p>
</section>
<section id="the-four-contenders" class="level2">
<h2 class="anchored" data-anchor-id="the-four-contenders">The four contenders</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Source</th>
<th>Output</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sapiens2-0.4b</strong></td>
<td><code>facebook/sapiens2-pose-0.4b</code></td>
<td>308 wholebody keypoints (Goliath scheme)</td>
<td>Meta’s 2026 SOTA on RGB. Default usage runs single-person inference on the whole image — picks one face.</td>
</tr>
<tr class="even">
<td><strong>DWPose</strong></td>
<td>RTMPose-x via <code>rtmlib</code></td>
<td>133 COCO-WholeBody</td>
<td><strong>Includes built-in YOLOX person detector.</strong> Multi-person friendly out of the box.</td>
</tr>
<tr class="odd">
<td><strong>MediaPipe FaceMesh</strong></td>
<td><code>face_landmarker.task</code> (v2)</td>
<td>478 face mesh points</td>
<td>CPU-class. Built-in BlazeFace short-range face detector; multi-face with <code>num_faces=N</code>.</td>
</tr>
<tr class="even">
<td><strong>ViTPose+ base</strong></td>
<td><code>usyd-community/vitpose-plus-base</code></td>
<td>17 COCO body keypoints</td>
<td>Body-only baseline (no face head on the HF checkpoint, even with <code>dataset_index=5</code>).</td>
</tr>
</tbody>
</table>
<p>All four take the <strong>full 192×256 frame</strong> as input — no upstream cropping. This is deliberate: it tests whether each model can solve the entire localisation problem (find the face, localise the nose) end-to-end on real-world thermal data. The hierarchical-detection version of this experiment is the subject of <a href="../posts/2026-05-20-thermal-nostril-hierarchical.html">part 3</a>.</p>
<p>For models that output multiple keypoints around the nose (Sapiens2 has 3 keypoints per nostril; MediaPipe has 4; DWPose has 5 in the nose-tip row), I average each model’s cluster to get a single “nose centre” per detected person. Indices are resolved <strong>by name</strong> from each model’s metadata — see the <a href="#">index-bug callout in v2</a> for why hardcoded indices burned me on the v1 SF-TL54 bake-off.</p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>One change that fixed the v1 of this post</strong>: looking up keypoint indices by name instead of hard-coding numbers. Sapiens2’s 308-keypoint Goliath scheme has <code>outer_corner_of_l_nostril</code> at index 186; the COCO-WholeBody scheme has its analog at index 58. Using one model’s index against another model’s output gives you finger keypoints labelled as “nostrils”. Always:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>n2i <span class="op">=</span> model.pose_metainfo[<span class="st">"keypoint_name2id"</span>]</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>nostril_l <span class="op">=</span> n2i[<span class="st">"outer_corner_of_l_nostril"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="matching-predictions-to-ground-truth" class="level2">
<h2 class="anchored" data-anchor-id="matching-predictions-to-ground-truth">Matching predictions to ground-truth</h2>
<p>ThermEval-D has multiple GT nose centroids per frame; some models return one prediction per detected person, others return one prediction per frame. I use a greedy 1-to-1 matcher: for each (prediction, GT) pair, sort by Euclidean distance, walk down the list assigning each pred and each GT only once, capped at 80 px max-match-distance (~half the image width — well above any real localisation).</p>
<p>Reported metrics:</p>
<ul>
<li><strong>Detection rate</strong> — fraction of GT noses for which the model produced <em>any</em> matched prediction (within 80 px).</li>
<li><strong>Mean / median nostril error</strong> — Euclidean px, <em>on matched predictions only</em>.</li>
<li><strong>PCK@k</strong> — fraction of GT noses for which a matched prediction lies within k px. Counts missed detections as 0 (so PCK@k ≤ detection rate). This is the strict version.</li>
</ul>
</section>
<section id="headline-result" class="level2">
<h2 class="anchored" data-anchor-id="headline-result">Headline result</h2>
<p>50 ThermEval-D frames; 73 ground-truth nose centroids across them.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nostril-bench/outputs/te_detection.png" class="img-fluid figure-img"></p>
<figcaption>Detection rate — what fraction of the 73 GT noses each model finds at all (within 80 px). DWPose finds every single one, including in 2-person frames; Sapiens2 finds the most prominent person in each frame; MediaPipe loses 86% of the GT because BlazeFace short-range can’t lock onto 20-px faces.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nostril-bench/outputs/te_pck10.png" class="img-fluid figure-img"></p>
<figcaption>Strict PCK\<span class="citation" data-cites="10px">@10px</span> — fraction of <em>all</em> GT noses for which the matched prediction lies within 10 px. Missed detections count as 0. This is the metric that actually matters for deployment.</figcaption>
</figure>
</div>
<p>The clean two-axis view of both:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nostril-bench/outputs/te_scatter.png" class="img-fluid figure-img"></p>
<figcaption>DWPose lives in the top-right (100% detection + 2.7 px median accuracy). Sapiens2 is accurate when it predicts (2 px median) but only finds 69% of the GT. MediaPipe has too few detections to compare on accuracy.</figcaption>
</figure>
</div>
<p>Three observations:</p>
<ol type="1">
<li><p><strong>DWPose’s win is about detection, not pixel precision.</strong> Sapiens2 has a 0.7 px lower median error <em>on the predictions it makes</em>, but it makes fewer predictions. The deployment metric (strict PCK@10) is dominated by detection rate.</p></li>
<li><p><strong>Sapiens2’s miss is a <em>coverage</em> problem, not an accuracy problem.</strong> Its default driver picks one person per frame. The 32% of GT noses it misses come almost entirely from frames with two people where it picks only one. Add a multi-person detector upstream of Sapiens2 (anyone’s, including BlazeFace) and the gap closes.</p></li>
<li><p><strong>MediaPipe’s miss is a <em>scale</em> problem.</strong> Its built-in BlazeFace short-range is tuned for selfie-distance faces (~50 px minimum). On ThermEval-D’s 20-px faces it returns no detections most of the time. Swapping to BlazeFace full-range (which I do in <a href="../posts/2026-05-20-thermal-nostril-hierarchical.html">part 3</a>) recovers most of the lost detections.</p></li>
</ol>
</section>
<section id="what-it-looks-like-six-representative-frames" class="level2">
<h2 class="anchored" data-anchor-id="what-it-looks-like-six-representative-frames">What it looks like — six representative frames</h2>
<p>Each row is one frame. The four panels (top-left clockwise) are Sapiens2-0.4b, DWPose, MediaPipe FaceMesh, ViTPose+. Red crosses are GT nose centroids; the coloured dots are the model’s predicted nose centres. Per-panel labels show match count, total predictions, and timing.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nostril-bench/outputs/te_six_frames.png" class="img-fluid figure-img"></p>
<figcaption>Six ThermEval-D frames × four models. DWPose (top-right of each cell) is the only one that consistently finds both noses in two-person frames. Sapiens2 (top-left) picks one face per frame — accurate when it picks, but it picks one. MediaPipe (bottom-left) misses most frames entirely.</figcaption>
</figure>
</div>
</section>
<section id="speed" class="level2">
<h2 class="anchored" data-anchor-id="speed">Speed</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nostril-bench/outputs/te_speed.png" class="img-fluid figure-img"></p>
<figcaption>Per-image wall-clock on a single RTX A5000, including model load. MediaPipe’s CPU inference is ~100× faster than the heavy GPU models, but at this resolution it’s also detecting almost nothing — its speed is irrelevant if it misses 86% of the GT.</figcaption>
</figure>
</div>
<p>Note that DWPose is actually slightly <em>slower</em> than Sapiens2 here — because DWPose’s pipeline includes a YOLOX person detection step (which is doing the work of finding multiple people), whereas Sapiens2 just does one forward pass per frame. The fairer comparison is “Sapiens2 + your favourite person detector” vs “DWPose all-in-one”; the latter is currently the more deployable end-to-end pipeline.</p>
</section>
<section id="why-mediapipes-number-looks-so-much-worse-than-on-the-sf-tl54-v2-of-this-post" class="level2">
<h2 class="anchored" data-anchor-id="why-mediapipes-number-looks-so-much-worse-than-on-the-sf-tl54-v2-of-this-post">Why MediaPipe’s number looks so much worse than on the SF-TL54 v2 of this post</h2>
<p>In the <a href="../posts/2026-05-20-thermal-nostril-bakeoff.html">previous (SF-TL54) version</a> of this post (now superseded), MediaPipe FaceMesh reported a 31 px mean error but <strong>100% detection rate</strong> — because SF-TL54 faces fill the frame (~150×150 px), and BlazeFace short-range works fine at that scale. The systematic 31 px error there was an <em>annotation-convention mismatch</em> (MediaPipe’s alae-centre vs SF-TL54’s sub-nasale row).</p>
<p>On ThermEval-D the failure mode is completely different: MediaPipe <strong>can’t find faces at all</strong> at 20 px, and what little it finds is roughly accurate (5.9 px mean on the 10/73 it detects). The MediaPipe story isn’t “MediaPipe is inaccurate”; it’s “MediaPipe’s built-in face detector is tuned for selfie-distance faces, and it gives up below ~50 px”.</p>
</section>
<section id="takeaways" class="level2">
<h2 class="anchored" data-anchor-id="takeaways">Takeaways</h2>
<ol type="1">
<li><p><strong>Choose the right benchmark.</strong> Numbers from controlled-portrait datasets (SF-TL54, Charlotte-ThermalFace) overstate how well off-the-shelf RGB-trained models handle thermal deployment, because they hide the small-face / multi-person reality. ThermEval-D is harder <em>and more realistic</em>.</p></li>
<li><p><strong>Detection rate first, sub-pixel precision second.</strong> A model that hits 2 px median accuracy on 60% of GT is <em>worse for deployment</em> than one with 3 px median on 100% of GT. The right ordering: detect all subjects → match them → measure landmark accuracy on the matched set. PCK@k over all GT (not just matched) captures this.</p></li>
<li><p><strong>DWPose is the right zero-shot deployment choice for thermal nostril localisation in real scenes.</strong> It bundles a person detector + 133-keypoint wholebody head, scales to multi-person, handles small faces, and is fast enough to run at video rate on a modest GPU.</p></li>
<li><p><strong>Sapiens2 isn’t a bad choice — it’s a <em>finetune-target</em> choice.</strong> Its 0.4B-param backbone produces excellent features. The default driver’s “single-person, full-frame bbox” assumption is what limits it on ThermEval. <a href="../posts/2026-05-20-thermal-nostril-finetune.html">Part 2</a> leverages exactly this: freeze the backbone, train a tiny head, get a deployable thermal-specialised model from 30 examples.</p></li>
<li><p><strong>MediaPipe is the right pick when you can guarantee a face crop of reasonable size.</strong> Use it as the second stage of a hierarchical pipeline (see <a href="../posts/2026-05-20-thermal-nostril-hierarchical.html">part 3</a>) — never as the single-stage detector on wide-field thermal.</p></li>
<li><p><strong>Always resolve keypoints by name.</strong> This post’s v1 reported Sapiens2 failing at 72 px on thermal because of a single hard-coded index that pointed at a finger landmark in the Goliath 308 scheme. The fix was a 3-line <code>keypoint_name2id</code> lookup. Add it to your model-loading code.</p></li>
</ol>
</section>
<section id="limitations-worth-being-explicit-about" class="level2">
<h2 class="anchored" data-anchor-id="limitations-worth-being-explicit-about">Limitations worth being explicit about</h2>
<ul>
<li><strong>ThermEval-D is one camera, one sensor.</strong> The TC001+ produces 256×192 thermal frames. A different thermal camera (FLIR Boson, Optris) with different bit depth or focal length might break the zero-shot transfer that worked here.</li>
<li><strong>The test set is 50 frames / 73 noses.</strong> I picked 50 frames for a quick first pass; running on the full split (∼287 frames with nose annotations) is straightforward but I haven’t done it. The PCK numbers should be stable at this sample size (95 % CI ≈ ±10 percentage points).</li>
<li><strong>All <code>Nose</code> annotations are single-point centroids derived from the polygon.</strong> ThermEval-D’s <code>Nose</code> polygon is the <em>external</em> nose surface — it isn’t anatomically the nostril alae (which would be slightly below). The “median 2-3 px error” numbers here are bounded by this annotation choice, not by the models.</li>
</ul>
</section>
<section id="links" class="level2">
<h2 class="anchored" data-anchor-id="links">Links</h2>
<ul>
<li>Dataset: <a href="https://www.kaggle.com/datasets/shriayush/thermeval">ThermEval on Kaggle</a> · <a href="https://sustainability-lab.github.io/thermeval/">ThermEval project page</a> · <a href="https://arxiv.org/abs/2602.14989">paper</a></li>
<li>Sapiens2: <a href="https://huggingface.co/facebook/sapiens2-pose-0.4b">facebook/sapiens2-pose-0.4b</a> · my earlier <a href="../posts/2026-04-25-sapiens2-on-mac.html">Sapiens2-on-Mac post</a></li>
<li>DWPose / RTMPose: <a href="https://github.com/Tau-J/rtmlib">rtmlib</a></li>
<li>MediaPipe Face Landmarker: <a href="https://developers.google.com/mediapipe/solutions/vision/face_landmarker">model card</a></li>
<li>ViTPose+: <a href="https://huggingface.co/docs/transformers/main/en/model_doc/vitpose">docs</a></li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            trigger: 'click',
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            positionFixed: true,
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "A Bake-off for Nostril Detection on Real-World Thermal Scenes (ThermEval-D)"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Nipun Batra"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-05-20"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="an">date-modified:</span><span class="co"> "2026-05-21"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [thermal-imaging, keypoint-detection, Sapiens2, DWPose, MediaPipe, ViTPose, pose-estimation, benchmark, breath-monitoring, ThermEval]</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Off-the-shelf wholebody pose / face mesh models on the ThermEval-D real-world thermal dataset (192x256, indoor multi-person scenes). On the smallest-face thermal regime that actually matches real deployment, DWPose wins decisively: 100% detection rate, 99% PCK@10px. Sapiens2-0.4b is accurate (2 px median on the noses it finds) but its single-person inference misses 32% of multi-person scenes. MediaPipe FaceMesh detects only 14% of GT noses because the 20-25 px faces in ThermEval are below BlazeFace short-range's working scale. The pipeline lesson is that for thermal deployment you need a model that includes its own multi-person face detector — not just a strong landmark head."</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: show</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="an">resources:</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - nostril-bench/scripts/*.py</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - nostril-bench/inputs/*.png</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - nostril-bench/outputs/*.png</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>**Update history:**</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**2026-05-20 (morning)** v1: Bake-off on SF-TL54 portraits with a hard-coded keypoint-index bug that made Sapiens2 look like it failed catastrophically.</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**2026-05-20 (afternoon)** v2: Fixed the index bug by looking up landmarks **by name** from <span class="in">`pose_metainfo`</span>. Both Sapiens2 and DWPose hit ~4 px on SF-TL54.</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**2026-05-21** (this version): Switched the dataset to [**ThermEval-D**](https://www.kaggle.com/datasets/shriayush/thermeval) (KDD 2026), which is much closer to real deployment — small faces, multi-person, indoor environments at 192×256 — rather than SF-TL54's controlled close-up portraits. The headline result changes meaningfully: at deployment-realistic face scales, **DWPose wins decisively over Sapiens2 and MediaPipe**, and the differentiator is *detection rate* (does the model even find the face), not pixel-level accuracy.</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>I want to detect **nostrils in thermal images** for breath-rate monitoring. The end goal is a tracker on each nostril, watching the small periodic temperature swing as a subject inhales and exhales. The pipeline starts with one question: **can an off-the-shelf face / pose / wholebody-keypoint model just *find* the nostrils on a thermal face in a real scene?**</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>This post answers that for four widely used models, on the <span class="co">[</span><span class="ot">ThermEval-D dataset</span><span class="co">](https://www.kaggle.com/datasets/shriayush/thermeval)</span> — a 1,049-frame thermal benchmark from the <span class="co">[</span><span class="ot">Sustainability Lab at IIT Gandhinagar</span><span class="co">](https://sustainability-lab.github.io/)</span> (KDD 2026), with per-pixel temperature, polygon-segmented <span class="in">`Person`</span> / <span class="in">`Chest`</span> / <span class="in">`Forehead`</span> / <span class="in">`Nose`</span> annotations, and an honest distribution of small faces in cluttered indoor scenes.</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>This is part 1 of a four-post series:</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**(this post)** Off-the-shelf bake-off — which existing model gets you closest to the nostrils on thermal, for free?</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span><span class="co">[</span><span class="ot">Finetuning Sapiens2 on 1-2 keypoints with a tiny labeled set</span><span class="co">](2026-05-20-thermal-nostril-finetune.qmd)</span>.</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span><span class="co">[</span><span class="ot">Hierarchical face → nostril detector</span><span class="co">](2026-05-20-thermal-nostril-hierarchical.qmd)</span> — why two stages beat one for tiny landmarks.</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span><span class="co">[</span><span class="ot">Why nostril detection on thermal is fundamentally harder than on RGB</span><span class="co">](2026-05-20-thermal-nostril-why-hard.qmd)</span>.</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Code: </span><span class="co">[</span><span class="ot">`posts/nostril-bench/scripts/`</span><span class="co">](https://github.com/nipunbatra/blog/tree/master/posts/nostril-bench/scripts)</span><span class="at"> — </span><span class="in">`run_all.py`</span><span class="at">, </span><span class="in">`run_thermeval.py`</span><span class="at">, </span><span class="in">`make_thermeval_charts.py`</span><span class="at">.</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a><span class="fu">## ThermEval-D — what's in it</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">ThermEval-D</span><span class="co">](https://www.kaggle.com/datasets/shriayush/thermeval)</span> is one of two components of the <span class="co">[</span><span class="ot">ThermEval benchmark</span><span class="co">](https://sustainability-lab.github.io/thermeval/)</span> (Sustainability Lab @ IIT Gandhinagar, KDD 2026). 1,049 thermal frames captured with a TOPDON TC001+ camera (sub-40 mK sensitivity, ±1°C accuracy), each:</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Image format**: 192×256 8-bit thermal PNG (visualisation) + a paired 16-bit <span class="in">`.tiff`</span> per-pixel radiometric temperature matrix.</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Annotations**: COCO format with four classes — <span class="in">`Person`</span>, <span class="in">`Chest`</span>, <span class="in">`Forehead`</span>, <span class="in">`Nose`</span> — each as polygon segmentations + bbox. Two annotation files (split 1: 510 frames, split 2: 538 frames).</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Distribution**: 256 of 510 frames in split 1 have all four classes; 83 frames have multiple <span class="in">`Person`</span> instances; ~287/510 have at least one <span class="in">`Nose`</span> annotation.</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>What "real-world" looks like in this dataset:</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>::: {layout-ncol=2}</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="al">![Two people at desks. The nose region is 5×7 px; the whole face is ~20×25 px in a 192×256 frame.](nostril-bench/inputs/sample_thermeval.png)</span>{#fig-sample-thermeval}</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a><span class="al">![Same frame with ground-truth annotations overlaid: Person bbox (blue), Forehead (yellow), Nose (green), nose centroid (red cross). Both faces have full annotations.](nostril-bench/inputs/sample_thermeval_annot.png)</span>{#fig-sample-thermeval-annot}</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>Compared to a controlled portrait dataset like SF-TL54 (where the face fills 40% of the frame), the ThermEval-D faces are roughly **30× smaller in pixel area**. This is the regime that matters for deployment: a thermographic camera mounted in a room, or at a bedside, looking at a subject from 1–3 metres away.</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## The four contenders</span></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Model <span class="pp">|</span> Source <span class="pp">|</span> Output <span class="pp">|</span> Notes <span class="pp">|</span></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a><span class="pp">|-------|--------|--------|-------|</span></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Sapiens2-0.4b** <span class="pp">|</span> <span class="in">`facebook/sapiens2-pose-0.4b`</span> <span class="pp">|</span> 308 wholebody keypoints (Goliath scheme) <span class="pp">|</span> Meta's 2026 SOTA on RGB. Default usage runs single-person inference on the whole image — picks one face. <span class="pp">|</span></span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **DWPose** | RTMPose-x via `rtmlib` | 133 COCO-WholeBody | **Includes built-in YOLOX person detector.** Multi-person friendly out of the box. <span class="pp">|</span></span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **MediaPipe FaceMesh** <span class="pp">|</span> <span class="in">`face_landmarker.task`</span> (v2) <span class="pp">|</span> 478 face mesh points <span class="pp">|</span> CPU-class. Built-in BlazeFace short-range face detector; multi-face with <span class="in">`num_faces=N`</span>. <span class="pp">|</span></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **ViTPose+ base** <span class="pp">|</span> <span class="in">`usyd-community/vitpose-plus-base`</span> <span class="pp">|</span> 17 COCO body keypoints <span class="pp">|</span> Body-only baseline (no face head on the HF checkpoint, even with <span class="in">`dataset_index=5`</span>). <span class="pp">|</span></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>All four take the **full 192×256 frame** as input — no upstream cropping. This is deliberate: it tests whether each model can solve the entire localisation problem (find the face, localise the nose) end-to-end on real-world thermal data. The hierarchical-detection version of this experiment is the subject of <span class="co">[</span><span class="ot">part 3</span><span class="co">](2026-05-20-thermal-nostril-hierarchical.qmd)</span>.</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>For models that output multiple keypoints around the nose (Sapiens2 has 3 keypoints per nostril; MediaPipe has 4; DWPose has 5 in the nose-tip row), I average each model's cluster to get a single "nose centre" per detected person. Indices are resolved **by name** from each model's metadata — see the <span class="co">[</span><span class="ot">index-bug callout in v2</span><span class="co">](#)</span> for why hardcoded indices burned me on the v1 SF-TL54 bake-off.</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip appearance="simple"}</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>**One change that fixed the v1 of this post**: looking up keypoint indices by name instead of hard-coding numbers. Sapiens2's 308-keypoint Goliath scheme has <span class="in">`outer_corner_of_l_nostril`</span> at index 186; the COCO-WholeBody scheme has its analog at index 58. Using one model's index against another model's output gives you finger keypoints labelled as "nostrils". Always:</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>n2i <span class="op">=</span> model.pose_metainfo[<span class="st">"keypoint_name2id"</span>]</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>nostril_l <span class="op">=</span> n2i[<span class="st">"outer_corner_of_l_nostril"</span>]</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a><span class="fu">## Matching predictions to ground-truth</span></span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a>ThermEval-D has multiple GT nose centroids per frame; some models return one prediction per detected person, others return one prediction per frame. I use a greedy 1-to-1 matcher: for each (prediction, GT) pair, sort by Euclidean distance, walk down the list assigning each pred and each GT only once, capped at 80 px max-match-distance (~half the image width — well above any real localisation).</span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a>Reported metrics:</span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Detection rate** — fraction of GT noses for which the model produced *any* matched prediction (within 80 px).</span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Mean / median nostril error** — Euclidean px, *on matched predictions only*.</span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**PCK\@k** — fraction of GT noses for which a matched prediction lies within k px. Counts missed detections as 0 (so PCK\@k ≤ detection rate). This is the strict version.</span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a><span class="fu">## Headline result</span></span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a>50 ThermEval-D frames; 73 ground-truth nose centroids across them.</span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a><span class="al">![Detection rate — what fraction of the 73 GT noses each model finds at all (within 80 px). DWPose finds every single one, including in 2-person frames; Sapiens2 finds the most prominent person in each frame; MediaPipe loses 86% of the GT because BlazeFace short-range can't lock onto 20-px faces.](nostril-bench/outputs/te_detection.png)</span></span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a><span class="al">![Strict PCK\\@10px — fraction of *all* GT noses for which the matched prediction lies within 10 px. Missed detections count as 0. This is the metric that actually matters for deployment.](nostril-bench/outputs/te_pck10.png)</span></span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a>The clean two-axis view of both:</span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a><span class="al">![DWPose lives in the top-right (100% detection + 2.7 px median accuracy). Sapiens2 is accurate when it predicts (2 px median) but only finds 69% of the GT. MediaPipe has too few detections to compare on accuracy.](nostril-bench/outputs/te_scatter.png)</span></span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a>Three observations:</span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**DWPose's win is about detection, not pixel precision.** Sapiens2 has a 0.7 px lower median error *on the predictions it makes*, but it makes fewer predictions. The deployment metric (strict PCK\@10) is dominated by detection rate.</span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Sapiens2's miss is a *coverage* problem, not an accuracy problem.** Its default driver picks one person per frame. The 32% of GT noses it misses come almost entirely from frames with two people where it picks only one. Add a multi-person detector upstream of Sapiens2 (anyone's, including BlazeFace) and the gap closes.</span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**MediaPipe's miss is a *scale* problem.** Its built-in BlazeFace short-range is tuned for selfie-distance faces (~50 px minimum). On ThermEval-D's 20-px faces it returns no detections most of the time. Swapping to BlazeFace full-range (which I do in <span class="co">[</span><span class="ot">part 3</span><span class="co">](2026-05-20-thermal-nostril-hierarchical.qmd)</span>) recovers most of the lost detections.</span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a><span class="fu">## What it looks like — six representative frames</span></span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a>Each row is one frame. The four panels (top-left clockwise) are Sapiens2-0.4b, DWPose, MediaPipe FaceMesh, ViTPose+. Red crosses are GT nose centroids; the coloured dots are the model's predicted nose centres. Per-panel labels show match count, total predictions, and timing.</span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a><span class="al">![Six ThermEval-D frames × four models. DWPose (top-right of each cell) is the only one that consistently finds both noses in two-person frames. Sapiens2 (top-left) picks one face per frame — accurate when it picks, but it picks one. MediaPipe (bottom-left) misses most frames entirely.](nostril-bench/outputs/te_six_frames.png)</span></span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a><span class="fu">## Speed</span></span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a><span class="al">![Per-image wall-clock on a single RTX A5000, including model load. MediaPipe's CPU inference is ~100× faster than the heavy GPU models, but at this resolution it's also detecting almost nothing — its speed is irrelevant if it misses 86% of the GT.](nostril-bench/outputs/te_speed.png)</span></span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a>Note that DWPose is actually slightly *slower* than Sapiens2 here — because DWPose's pipeline includes a YOLOX person detection step (which is doing the work of finding multiple people), whereas Sapiens2 just does one forward pass per frame. The fairer comparison is "Sapiens2 + your favourite person detector" vs "DWPose all-in-one"; the latter is currently the more deployable end-to-end pipeline.</span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why MediaPipe's number looks so much worse than on the SF-TL54 v2 of this post</span></span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a>In the <span class="co">[</span><span class="ot">previous (SF-TL54) version</span><span class="co">](2026-05-20-thermal-nostril-bakeoff.qmd)</span> of this post (now superseded), MediaPipe FaceMesh reported a 31 px mean error but **100% detection rate** — because SF-TL54 faces fill the frame (~150×150 px), and BlazeFace short-range works fine at that scale. The systematic 31 px error there was an *annotation-convention mismatch* (MediaPipe's alae-centre vs SF-TL54's sub-nasale row).</span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a>On ThermEval-D the failure mode is completely different: MediaPipe **can't find faces at all** at 20 px, and what little it finds is roughly accurate (5.9 px mean on the 10/73 it detects). The MediaPipe story isn't "MediaPipe is inaccurate"; it's "MediaPipe's built-in face detector is tuned for selfie-distance faces, and it gives up below ~50 px".</span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a><span class="fu">## Takeaways</span></span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Choose the right benchmark.** Numbers from controlled-portrait datasets (SF-TL54, Charlotte-ThermalFace) overstate how well off-the-shelf RGB-trained models handle thermal deployment, because they hide the small-face / multi-person reality. ThermEval-D is harder *and more realistic*.</span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Detection rate first, sub-pixel precision second.** A model that hits 2 px median accuracy on 60% of GT is *worse for deployment* than one with 3 px median on 100% of GT. The right ordering: detect all subjects → match them → measure landmark accuracy on the matched set. PCK\@k over all GT (not just matched) captures this.</span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**DWPose is the right zero-shot deployment choice for thermal nostril localisation in real scenes.** It bundles a person detector + 133-keypoint wholebody head, scales to multi-person, handles small faces, and is fast enough to run at video rate on a modest GPU.</span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Sapiens2 isn't a bad choice — it's a *finetune-target* choice.** Its 0.4B-param backbone produces excellent features. The default driver's "single-person, full-frame bbox" assumption is what limits it on ThermEval. <span class="co">[</span><span class="ot">Part 2</span><span class="co">](2026-05-20-thermal-nostril-finetune.qmd)</span> leverages exactly this: freeze the backbone, train a tiny head, get a deployable thermal-specialised model from 30 examples.</span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-137"><a href="#cb2-137" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**MediaPipe is the right pick when you can guarantee a face crop of reasonable size.** Use it as the second stage of a hierarchical pipeline (see <span class="co">[</span><span class="ot">part 3</span><span class="co">](2026-05-20-thermal-nostril-hierarchical.qmd)</span>) — never as the single-stage detector on wide-field thermal.</span>
<span id="cb2-138"><a href="#cb2-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Always resolve keypoints by name.** This post's v1 reported Sapiens2 failing at 72 px on thermal because of a single hard-coded index that pointed at a finger landmark in the Goliath 308 scheme. The fix was a 3-line <span class="in">`keypoint_name2id`</span> lookup. Add it to your model-loading code.</span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitations worth being explicit about</span></span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**ThermEval-D is one camera, one sensor.** The TC001+ produces 256×192 thermal frames. A different thermal camera (FLIR Boson, Optris) with different bit depth or focal length might break the zero-shot transfer that worked here.</span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The test set is 50 frames / 73 noses.** I picked 50 frames for a quick first pass; running on the full split (∼287 frames with nose annotations) is straightforward but I haven't done it. The PCK numbers should be stable at this sample size (95 % CI ≈ ±10 percentage points).</span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**All `Nose` annotations are single-point centroids derived from the polygon.** ThermEval-D's <span class="in">`Nose`</span> polygon is the *external* nose surface — it isn't anatomically the nostril alae (which would be slightly below). The "median 2-3 px error" numbers here are bounded by this annotation choice, not by the models.</span>
<span id="cb2-146"><a href="#cb2-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-147"><a href="#cb2-147" aria-hidden="true" tabindex="-1"></a><span class="fu">## Links</span></span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Dataset: <span class="co">[</span><span class="ot">ThermEval on Kaggle</span><span class="co">](https://www.kaggle.com/datasets/shriayush/thermeval)</span> · <span class="co">[</span><span class="ot">ThermEval project page</span><span class="co">](https://sustainability-lab.github.io/thermeval/)</span> · <span class="co">[</span><span class="ot">paper</span><span class="co">](https://arxiv.org/abs/2602.14989)</span></span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Sapiens2: <span class="co">[</span><span class="ot">facebook/sapiens2-pose-0.4b</span><span class="co">](https://huggingface.co/facebook/sapiens2-pose-0.4b)</span> · my earlier <span class="co">[</span><span class="ot">Sapiens2-on-Mac post</span><span class="co">](2026-04-25-sapiens2-on-mac.qmd)</span></span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>DWPose / RTMPose: <span class="co">[</span><span class="ot">rtmlib</span><span class="co">](https://github.com/Tau-J/rtmlib)</span></span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>MediaPipe Face Landmarker: <span class="co">[</span><span class="ot">model card</span><span class="co">](https://developers.google.com/mediapipe/solutions/vision/face_landmarker)</span></span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>ViTPose+: <span class="co">[</span><span class="ot">docs</span><span class="co">](https://huggingface.co/docs/transformers/main/en/model_doc/vitpose)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Nipun Batra</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/nipunbatra">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>